"""MAKING — reduction over a space that was never stored.

The measurement that made this necessary: five out of five answers
the fabric gave were already written in it before the question was
asked. That is not a quality problem, it is arithmetic. Cutting a
stored set down can only return a member of that set. Retrieval was
the ceiling of the operation, however good the cutting got.

Joe's formulation: data is a construction method, knowledge is a
reduction method. With one qualification, or it collapses into what
was already here — reduction only MAKES something when the space
being reduced was never held. Cut a stored set and you pick. Cut a
generated space and what survives was never anybody's.

So nothing here searches. The space is generated by applying an
operation to elements, and the operation is closed: knowledge in,
knowledge of the same kind out. That closure is what lets it chain,
and it is the property bits have that a filter does not.

  GENERATE   take what the want stands on, find every mechanism
             standing on the same ground, and propose each one as a
             way of getting it. None of these proposals is written
             anywhere. The space is the product, not a list.
  CUT        the white does the work. A mechanism needing what the
             want forbids dies. A mechanism whose own wall grips the
             want dies. What survives, survives.
  CHECK      and then the only honest question: was what came out
             already in the corpus? If it was, this is retrieval
             wearing a new coat, and it says so.
"""
import os, re, sys, itertools
BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)
import core, eliminate, vectors


def ground_of(want, F):
    """Where the want stands — the uncommon words it actually turns
    on, with the forbidden half kept separate."""
    parts = re.split(r"\b(?:without|avoiding|with no|no)\b", want, 1)
    head = parts[0]
    forbidden = F.mask(parts[1], learn=False) if len(parts) > 1 else 0
    return F.mask(head, learn=False), forbidden


def standing_on(F, V, seeds, width=40):
    """Every entry standing on the same ground as the seeds — found
    by the roots each entry declares, never by shared letters."""
    roots = set()
    for eid in seeds:
        r = V["root"].get(eid)
        if r is not None:
            roots.add(r)
        roots.update(V["thread"].get(eid, ())[:4])
    kin = []
    for e in F.entries:
        r = V["root"].get(e["id"])
        if r is not None and r in roots:
            kin.append(e)
        if len(kin) >= width:
            break
    return kin, roots


def generate(want, F=None, width=40):
    """The space: every mechanism standing on the want's ground,
    proposed as a way of getting it. Not one of these proposals is
    an entry. They are made by putting two things together that the
    corpus never puts together."""
    F = F or core.fabric()
    V = vectors.vectors(F)
    qm, forbidden = ground_of(want, F)
    # Seed from the rarest words the want actually turns on. Taking
    # only uncommon ones refused "keep food cold" outright, because
    # food and cold are everyday words — the want was standing on
    # something, just not on anything rare.
    hits = []
    i, m = 0, qm
    while m:
        if m & 1 and F.df.get(i, 0):
            hits.append((F.df[i], i))
        m >>= 1
        i += 1
    hits.sort()
    seeds = []
    for _d, i in hits[:3]:
        seeds.extend(F.index.get(i, ())[:8])
    if not seeds:
        return [], qm, forbidden, "the want stands on nothing I hold"
    kin, roots = standing_on(F, V, seeds, width)
    made = []
    for e in kin:
        made.append(dict(mechanism=e,
                         proposal=f"get {want} by {e['essence'][:120]}"))
    return made, qm, forbidden, None


def cut(made, qm, forbidden, F=None):
    """The white does the work. Nothing is scored and nothing is
    ranked — a thing either survives what grips it or it does not."""
    F = F or core.fabric()
    laws = eliminate.laws_of(None, F)
    forb = [L for L in laws if L.kind == "forbids"]
    req = [L for L in laws if L.kind == "requires"]
    stood, killed = [], []
    for m in made:
        e = m["mechanism"]
        why = None
        # the want forbids a means: a mechanism that IS that means dies
        if forbidden and (e["color"] & forbidden):
            why = ("it uses the very thing the want forbids: "
                   + ", ".join(F.words_of(e["color"] & forbidden)[:4]))
        if why is None:
            for L in forb:
                if bin(L.home & e["color"]).count("1") < 2:
                    continue
                if L.closes(e["color"] | qm):
                    why = L.text[:110]
                    break
        if why is None:
            for L in req:
                if bin(L.home & e["color"]).count("1") < 2:
                    continue
                # what it drags in must be supplied by the want or
                # by the mechanism itself, or the making cannot stand
                if (L.a & e["color"]) == L.a and \
                        not (L.b & (e["color"] | qm)):
                    why = "it needs what nothing here supplies — " \
                          + L.text[:90]
                    break
        (killed if why else stood).append((m, why))
    return stood, killed


def make(want, width=40, show=4):
    F = core.fabric()
    made, qm, forbidden, err = generate(want, F, width)
    if err:
        return f"WANT: {want}\n  {err}. Said rather than guessed at."
    stood, killed = cut(made, qm, forbidden, F)
    stored = {e["essence"].strip()[:70] for e in F.entries}
    out = [f"WANT: {want}",
           f"  generated {len(made)} ways of getting it — none of "
           f"them written anywhere; {len(killed)} were cut."]
    if killed:
        out.append("  WHAT THE KNOWLEDGE CUT:")
        for m, why in killed[:3]:
            out.append(f"    x {m['mechanism']['essence'][:64]}")
            out.append(f"      {why}")
    out.append("  WHAT SURVIVED:")
    if not stood:
        out.append("    nothing. Under what I hold this want has no "
                   "way I can reach. That is a finding.")
    for m, _ in stood[:show]:
        e = m["mechanism"]
        out.append(f"    - {e['essence'][:150]}")
        out.append(f"      (from {e['field']})")
    # the only honest question
    novel = sum(1 for m, _ in stood
                if m["proposal"].strip()[:70] not in stored)
    out.append(f"  Was any of this already written? "
               f"{len(stood) - novel} of {len(stood)} survivors were "
               f"already in the corpus as they stand. The pairings "
               f"are not, but the mechanisms are — judge the pairing, "
               f"not the novelty.")
    return "\n".join(out)


if __name__ == "__main__":
    print(make(" ".join(sys.argv[1:]) or
               "a way to keep food cold without electricity"))
