[package]
name = "guala_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "guala_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module", "num-complex"] }
num-complex = "0.4"

[profile.release]
lto = true
codegen-units = 1
