// Auto-generated from external screener schema capture (view v=111).
// Captured: 2026-02-25T03:15:34.040894+00:00

export type ScreenerAdvancedFilterKey =
  | "exchange"
  | "index"
  | "sector"
  | "industry"
  | "country"
  | "marketCap"
  | "dividendYield"
  | "shortFloat"
  | "analystRecom"
  | "optionShort"
  | "earningsDate"
  | "avgVolume"
  | "relVolume"
  | "currentVolume"
  | "trades"
  | "priceBand"
  | "targetPrice"
  | "ipoDate"
  | "sharesOutstanding"
  | "float"
  | "theme"
  | "subTheme";

export type ScreenerFilterOption = {
  value: string;
  label: string;
  eliteOnly: boolean;
};

export const SCREENER_V111_FILTER_OPTIONS: Record<ScreenerAdvancedFilterKey, ScreenerFilterOption[]> = {
  exchange: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "amex", label: "AMEX", eliteOnly: false },
    { value: "cboe", label: "CBOE", eliteOnly: false },
    { value: "nasd", label: "NASDAQ", eliteOnly: false },
    { value: "nyse", label: "NYSE", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  index: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "sp500", label: "S&P 500", eliteOnly: false },
    { value: "ndx", label: "NASDAQ 100", eliteOnly: false },
    { value: "dji", label: "DJIA", eliteOnly: false },
    { value: "rut", label: "RUSSELL 2000", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  sector: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "basicmaterials", label: "Basic Materials", eliteOnly: false },
    { value: "communicationservices", label: "Communication Services", eliteOnly: false },
    { value: "consumercyclical", label: "Consumer Cyclical", eliteOnly: false },
    { value: "consumerdefensive", label: "Consumer Defensive", eliteOnly: false },
    { value: "energy", label: "Energy", eliteOnly: false },
    { value: "financial", label: "Financial", eliteOnly: false },
    { value: "healthcare", label: "Healthcare", eliteOnly: false },
    { value: "industrials", label: "Industrials", eliteOnly: false },
    { value: "realestate", label: "Real Estate", eliteOnly: false },
    { value: "technology", label: "Technology", eliteOnly: false },
    { value: "utilities", label: "Utilities", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  industry: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "stocksonly", label: "Stocks only (ex-Funds)", eliteOnly: false },
    { value: "exchangetradedfund", label: "Exchange Traded Fund", eliteOnly: false },
    { value: "advertisingagencies", label: "Advertising Agencies", eliteOnly: false },
    { value: "aerospacedefense", label: "Aerospace & Defense", eliteOnly: false },
    { value: "agriculturalinputs", label: "Agricultural Inputs", eliteOnly: false },
    { value: "airlines", label: "Airlines", eliteOnly: false },
    { value: "airportsairservices", label: "Airports & Air Services", eliteOnly: false },
    { value: "aluminum", label: "Aluminum", eliteOnly: false },
    { value: "apparelmanufacturing", label: "Apparel Manufacturing", eliteOnly: false },
    { value: "apparelretail", label: "Apparel Retail", eliteOnly: false },
    { value: "assetmanagement", label: "Asset Management", eliteOnly: false },
    { value: "automanufacturers", label: "Auto Manufacturers", eliteOnly: false },
    { value: "autoparts", label: "Auto Parts", eliteOnly: false },
    { value: "autotruckdealerships", label: "Auto & Truck Dealerships", eliteOnly: false },
    { value: "banksdiversified", label: "Banks - Diversified", eliteOnly: false },
    { value: "banksregional", label: "Banks - Regional", eliteOnly: false },
    { value: "beveragesbrewers", label: "Beverages - Brewers", eliteOnly: false },
    { value: "beveragesnonalcoholic", label: "Beverages - Non-Alcoholic", eliteOnly: false },
    { value: "beverageswineriesdistilleries", label: "Beverages - Wineries & Distilleries", eliteOnly: false },
    { value: "biotechnology", label: "Biotechnology", eliteOnly: false },
    { value: "broadcasting", label: "Broadcasting", eliteOnly: false },
    { value: "buildingmaterials", label: "Building Materials", eliteOnly: false },
    { value: "buildingproductsequipment", label: "Building Products & Equipment", eliteOnly: false },
    { value: "businessequipmentsupplies", label: "Business Equipment & Supplies", eliteOnly: false },
    { value: "capitalmarkets", label: "Capital Markets", eliteOnly: false },
    { value: "chemicals", label: "Chemicals", eliteOnly: false },
    { value: "closedendfunddebt", label: "Closed-End Fund - Debt", eliteOnly: false },
    { value: "closedendfundequity", label: "Closed-End Fund - Equity", eliteOnly: false },
    { value: "closedendfundforeign", label: "Closed-End Fund - Foreign", eliteOnly: false },
    { value: "cokingcoal", label: "Coking Coal", eliteOnly: false },
    { value: "communicationequipment", label: "Communication Equipment", eliteOnly: false },
    { value: "computerhardware", label: "Computer Hardware", eliteOnly: false },
    { value: "confectioners", label: "Confectioners", eliteOnly: false },
    { value: "conglomerates", label: "Conglomerates", eliteOnly: false },
    { value: "consultingservices", label: "Consulting Services", eliteOnly: false },
    { value: "consumerelectronics", label: "Consumer Electronics", eliteOnly: false },
    { value: "copper", label: "Copper", eliteOnly: false },
    { value: "creditservices", label: "Credit Services", eliteOnly: false },
    { value: "departmentstores", label: "Department Stores", eliteOnly: false },
    { value: "diagnosticsresearch", label: "Diagnostics & Research", eliteOnly: false },
    { value: "discountstores", label: "Discount Stores", eliteOnly: false },
    { value: "drugmanufacturersgeneral", label: "Drug Manufacturers - General", eliteOnly: false },
    { value: "drugmanufacturersspecialtygeneric", label: "Drug Manufacturers - Specialty & Generic", eliteOnly: false },
    { value: "educationtrainingservices", label: "Education & Training Services", eliteOnly: false },
    { value: "electricalequipmentparts", label: "Electrical Equipment & Parts", eliteOnly: false },
    { value: "electroniccomponents", label: "Electronic Components", eliteOnly: false },
    { value: "electronicgamingmultimedia", label: "Electronic Gaming & Multimedia", eliteOnly: false },
    { value: "electronicscomputerdistribution", label: "Electronics & Computer Distribution", eliteOnly: false },
    { value: "engineeringconstruction", label: "Engineering & Construction", eliteOnly: false },
    { value: "entertainment", label: "Entertainment", eliteOnly: false },
    { value: "exchangetradedfund", label: "Exchange Traded Fund", eliteOnly: false },
    { value: "farmheavyconstructionmachinery", label: "Farm & Heavy Construction Machinery", eliteOnly: false },
    { value: "farmproducts", label: "Farm Products", eliteOnly: false },
    { value: "financialconglomerates", label: "Financial Conglomerates", eliteOnly: false },
    { value: "financialdatastockexchanges", label: "Financial Data & Stock Exchanges", eliteOnly: false },
    { value: "fooddistribution", label: "Food Distribution", eliteOnly: false },
    { value: "footwearaccessories", label: "Footwear & Accessories", eliteOnly: false },
    { value: "furnishingsfixturesappliances", label: "Furnishings, Fixtures & Appliances", eliteOnly: false },
    { value: "gambling", label: "Gambling", eliteOnly: false },
    { value: "gold", label: "Gold", eliteOnly: false },
    { value: "grocerystores", label: "Grocery Stores", eliteOnly: false },
    { value: "healthcareplans", label: "Healthcare Plans", eliteOnly: false },
    { value: "healthinformationservices", label: "Health Information Services", eliteOnly: false },
    { value: "homeimprovementretail", label: "Home Improvement Retail", eliteOnly: false },
    { value: "householdpersonalproducts", label: "Household & Personal Products", eliteOnly: false },
    { value: "industrialdistribution", label: "Industrial Distribution", eliteOnly: false },
    { value: "informationtechnologyservices", label: "Information Technology Services", eliteOnly: false },
    { value: "infrastructureoperations", label: "Infrastructure Operations", eliteOnly: false },
    { value: "insurancebrokers", label: "Insurance Brokers", eliteOnly: false },
    { value: "insurancediversified", label: "Insurance - Diversified", eliteOnly: false },
    { value: "insurancelife", label: "Insurance - Life", eliteOnly: false },
    { value: "insurancepropertycasualty", label: "Insurance - Property & Casualty", eliteOnly: false },
    { value: "insurancereinsurance", label: "Insurance - Reinsurance", eliteOnly: false },
    { value: "insurancespecialty", label: "Insurance - Specialty", eliteOnly: false },
    { value: "integratedfreightlogistics", label: "Integrated Freight & Logistics", eliteOnly: false },
    { value: "internetcontentinformation", label: "Internet Content & Information", eliteOnly: false },
    { value: "internetretail", label: "Internet Retail", eliteOnly: false },
    { value: "leisure", label: "Leisure", eliteOnly: false },
    { value: "lodging", label: "Lodging", eliteOnly: false },
    { value: "lumberwoodproduction", label: "Lumber & Wood Production", eliteOnly: false },
    { value: "luxurygoods", label: "Luxury Goods", eliteOnly: false },
    { value: "marineshipping", label: "Marine Shipping", eliteOnly: false },
    { value: "medicalcarefacilities", label: "Medical Care Facilities", eliteOnly: false },
    { value: "medicaldevices", label: "Medical Devices", eliteOnly: false },
    { value: "medicaldistribution", label: "Medical Distribution", eliteOnly: false },
    { value: "medicalinstrumentssupplies", label: "Medical Instruments & Supplies", eliteOnly: false },
    { value: "metalfabrication", label: "Metal Fabrication", eliteOnly: false },
    { value: "mortgagefinance", label: "Mortgage Finance", eliteOnly: false },
    { value: "oilgasdrilling", label: "Oil & Gas Drilling", eliteOnly: false },
    { value: "oilgasep", label: "Oil & Gas E&P", eliteOnly: false },
    { value: "oilgasequipmentservices", label: "Oil & Gas Equipment & Services", eliteOnly: false },
    { value: "oilgasintegrated", label: "Oil & Gas Integrated", eliteOnly: false },
    { value: "oilgasmidstream", label: "Oil & Gas Midstream", eliteOnly: false },
    { value: "oilgasrefiningmarketing", label: "Oil & Gas Refining & Marketing", eliteOnly: false },
    { value: "otherindustrialmetalsmining", label: "Other Industrial Metals & Mining", eliteOnly: false },
    { value: "otherpreciousmetalsmining", label: "Other Precious Metals & Mining", eliteOnly: false },
    { value: "packagedfoods", label: "Packaged Foods", eliteOnly: false },
    { value: "packagingcontainers", label: "Packaging & Containers", eliteOnly: false },
    { value: "paperpaperproducts", label: "Paper & Paper Products", eliteOnly: false },
    { value: "personalservices", label: "Personal Services", eliteOnly: false },
    { value: "pharmaceuticalretailers", label: "Pharmaceutical Retailers", eliteOnly: false },
    { value: "pollutiontreatmentcontrols", label: "Pollution & Treatment Controls", eliteOnly: false },
    { value: "publishing", label: "Publishing", eliteOnly: false },
    { value: "railroads", label: "Railroads", eliteOnly: false },
    { value: "realestatedevelopment", label: "Real Estate - Development", eliteOnly: false },
    { value: "realestatediversified", label: "Real Estate - Diversified", eliteOnly: false },
    { value: "realestateservices", label: "Real Estate Services", eliteOnly: false },
    { value: "recreationalvehicles", label: "Recreational Vehicles", eliteOnly: false },
    { value: "reitdiversified", label: "REIT - Diversified", eliteOnly: false },
    { value: "reithealthcarefacilities", label: "REIT - Healthcare Facilities", eliteOnly: false },
    { value: "reithotelmotel", label: "REIT - Hotel & Motel", eliteOnly: false },
    { value: "reitindustrial", label: "REIT - Industrial", eliteOnly: false },
    { value: "reitmortgage", label: "REIT - Mortgage", eliteOnly: false },
    { value: "reitoffice", label: "REIT - Office", eliteOnly: false },
    { value: "reitresidential", label: "REIT - Residential", eliteOnly: false },
    { value: "reitretail", label: "REIT - Retail", eliteOnly: false },
    { value: "reitspecialty", label: "REIT - Specialty", eliteOnly: false },
    { value: "rentalleasingservices", label: "Rental & Leasing Services", eliteOnly: false },
    { value: "residentialconstruction", label: "Residential Construction", eliteOnly: false },
    { value: "resortscasinos", label: "Resorts & Casinos", eliteOnly: false },
    { value: "restaurants", label: "Restaurants", eliteOnly: false },
    { value: "scientifictechnicalinstruments", label: "Scientific & Technical Instruments", eliteOnly: false },
    { value: "securityprotectionservices", label: "Security & Protection Services", eliteOnly: false },
    { value: "semiconductorequipmentmaterials", label: "Semiconductor Equipment & Materials", eliteOnly: false },
    { value: "semiconductors", label: "Semiconductors", eliteOnly: false },
    { value: "shellcompanies", label: "Shell Companies", eliteOnly: false },
    { value: "silver", label: "Silver", eliteOnly: false },
    { value: "softwareapplication", label: "Software - Application", eliteOnly: false },
    { value: "softwareinfrastructure", label: "Software - Infrastructure", eliteOnly: false },
    { value: "solar", label: "Solar", eliteOnly: false },
    { value: "specialtybusinessservices", label: "Specialty Business Services", eliteOnly: false },
    { value: "specialtychemicals", label: "Specialty Chemicals", eliteOnly: false },
    { value: "specialtyindustrialmachinery", label: "Specialty Industrial Machinery", eliteOnly: false },
    { value: "specialtyretail", label: "Specialty Retail", eliteOnly: false },
    { value: "staffingemploymentservices", label: "Staffing & Employment Services", eliteOnly: false },
    { value: "steel", label: "Steel", eliteOnly: false },
    { value: "telecomservices", label: "Telecom Services", eliteOnly: false },
    { value: "textilemanufacturing", label: "Textile Manufacturing", eliteOnly: false },
    { value: "thermalcoal", label: "Thermal Coal", eliteOnly: false },
    { value: "tobacco", label: "Tobacco", eliteOnly: false },
    { value: "toolsaccessories", label: "Tools & Accessories", eliteOnly: false },
    { value: "travelservices", label: "Travel Services", eliteOnly: false },
    { value: "trucking", label: "Trucking", eliteOnly: false },
    { value: "uranium", label: "Uranium", eliteOnly: false },
    { value: "utilitiesdiversified", label: "Utilities - Diversified", eliteOnly: false },
    { value: "utilitiesindependentpowerproducers", label: "Utilities - Independent Power Producers", eliteOnly: false },
    { value: "utilitiesregulatedelectric", label: "Utilities - Regulated Electric", eliteOnly: false },
    { value: "utilitiesregulatedgas", label: "Utilities - Regulated Gas", eliteOnly: false },
    { value: "utilitiesregulatedwater", label: "Utilities - Regulated Water", eliteOnly: false },
    { value: "utilitiesrenewable", label: "Utilities - Renewable", eliteOnly: false },
    { value: "wastemanagement", label: "Waste Management", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  country: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "usa", label: "USA", eliteOnly: false },
    { value: "notusa", label: "Foreign (ex-USA)", eliteOnly: false },
    { value: "asia", label: "Asia", eliteOnly: false },
    { value: "europe", label: "Europe", eliteOnly: false },
    { value: "latinamerica", label: "Latin America", eliteOnly: false },
    { value: "bric", label: "BRIC", eliteOnly: false },
    { value: "argentina", label: "Argentina", eliteOnly: false },
    { value: "australia", label: "Australia", eliteOnly: false },
    { value: "bahamas", label: "Bahamas", eliteOnly: false },
    { value: "belgium", label: "Belgium", eliteOnly: false },
    { value: "benelux", label: "BeNeLux", eliteOnly: false },
    { value: "bermuda", label: "Bermuda", eliteOnly: false },
    { value: "brazil", label: "Brazil", eliteOnly: false },
    { value: "canada", label: "Canada", eliteOnly: false },
    { value: "caymanislands", label: "Cayman Islands", eliteOnly: false },
    { value: "chile", label: "Chile", eliteOnly: false },
    { value: "china", label: "China", eliteOnly: false },
    { value: "chinahongkong", label: "China & Hong Kong", eliteOnly: false },
    { value: "colombia", label: "Colombia", eliteOnly: false },
    { value: "cyprus", label: "Cyprus", eliteOnly: false },
    { value: "denmark", label: "Denmark", eliteOnly: false },
    { value: "finland", label: "Finland", eliteOnly: false },
    { value: "france", label: "France", eliteOnly: false },
    { value: "germany", label: "Germany", eliteOnly: false },
    { value: "greece", label: "Greece", eliteOnly: false },
    { value: "hongkong", label: "Hong Kong", eliteOnly: false },
    { value: "hungary", label: "Hungary", eliteOnly: false },
    { value: "iceland", label: "Iceland", eliteOnly: false },
    { value: "india", label: "India", eliteOnly: false },
    { value: "indonesia", label: "Indonesia", eliteOnly: false },
    { value: "ireland", label: "Ireland", eliteOnly: false },
    { value: "israel", label: "Israel", eliteOnly: false },
    { value: "italy", label: "Italy", eliteOnly: false },
    { value: "japan", label: "Japan", eliteOnly: false },
    { value: "jordan", label: "Jordan", eliteOnly: false },
    { value: "kazakhstan", label: "Kazakhstan", eliteOnly: false },
    { value: "luxembourg", label: "Luxembourg", eliteOnly: false },
    { value: "malaysia", label: "Malaysia", eliteOnly: false },
    { value: "malta", label: "Malta", eliteOnly: false },
    { value: "mexico", label: "Mexico", eliteOnly: false },
    { value: "monaco", label: "Monaco", eliteOnly: false },
    { value: "netherlands", label: "Netherlands", eliteOnly: false },
    { value: "newzealand", label: "New Zealand", eliteOnly: false },
    { value: "norway", label: "Norway", eliteOnly: false },
    { value: "panama", label: "Panama", eliteOnly: false },
    { value: "peru", label: "Peru", eliteOnly: false },
    { value: "philippines", label: "Philippines", eliteOnly: false },
    { value: "portugal", label: "Portugal", eliteOnly: false },
    { value: "russia", label: "Russia", eliteOnly: false },
    { value: "singapore", label: "Singapore", eliteOnly: false },
    { value: "southafrica", label: "South Africa", eliteOnly: false },
    { value: "southkorea", label: "South Korea", eliteOnly: false },
    { value: "spain", label: "Spain", eliteOnly: false },
    { value: "sweden", label: "Sweden", eliteOnly: false },
    { value: "switzerland", label: "Switzerland", eliteOnly: false },
    { value: "taiwan", label: "Taiwan", eliteOnly: false },
    { value: "thailand", label: "Thailand", eliteOnly: false },
    { value: "turkey", label: "Turkey", eliteOnly: false },
    { value: "unitedarabemirates", label: "United Arab Emirates", eliteOnly: false },
    { value: "unitedkingdom", label: "United Kingdom", eliteOnly: false },
    { value: "uruguay", label: "Uruguay", eliteOnly: false },
    { value: "vietnam", label: "Vietnam", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  marketCap: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "mega", label: "Mega ($200bln and more)", eliteOnly: false },
    { value: "large", label: "Large ($10bln to $200bln)", eliteOnly: false },
    { value: "mid", label: "Mid ($2bln to $10bln)", eliteOnly: false },
    { value: "small", label: "Small ($300mln to $2bln)", eliteOnly: false },
    { value: "micro", label: "Micro ($50mln to $300mln)", eliteOnly: false },
    { value: "nano", label: "Nano (under $50mln)", eliteOnly: false },
    { value: "largeover", label: "+Large (over $10bln)", eliteOnly: false },
    { value: "midover", label: "+Mid (over $2bln)", eliteOnly: false },
    { value: "smallover", label: "+Small (over $300mln)", eliteOnly: false },
    { value: "microover", label: "+Micro (over $50mln)", eliteOnly: false },
    { value: "largeunder", label: "-Large (under $200bln)", eliteOnly: false },
    { value: "midunder", label: "-Mid (under $10bln)", eliteOnly: false },
    { value: "smallunder", label: "-Small (under $2bln)", eliteOnly: false },
    { value: "microunder", label: "-Micro (under $300mln)", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  dividendYield: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "none", label: "None (0%)", eliteOnly: false },
    { value: "pos", label: "Positive (>0%)", eliteOnly: false },
    { value: "high", label: "High (>5%)", eliteOnly: false },
    { value: "veryhigh", label: "Very High (>10%)", eliteOnly: false },
    { value: "o1", label: "Over 1%", eliteOnly: false },
    { value: "o2", label: "Over 2%", eliteOnly: false },
    { value: "o3", label: "Over 3%", eliteOnly: false },
    { value: "o4", label: "Over 4%", eliteOnly: false },
    { value: "o5", label: "Over 5%", eliteOnly: false },
    { value: "o6", label: "Over 6%", eliteOnly: false },
    { value: "o7", label: "Over 7%", eliteOnly: false },
    { value: "o8", label: "Over 8%", eliteOnly: false },
    { value: "o9", label: "Over 9%", eliteOnly: false },
    { value: "o10", label: "Over 10%", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  shortFloat: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "low", label: "Low (<5%)", eliteOnly: false },
    { value: "high", label: "High (>20%)", eliteOnly: false },
    { value: "u5", label: "Under 5%", eliteOnly: false },
    { value: "u10", label: "Under 10%", eliteOnly: false },
    { value: "u15", label: "Under 15%", eliteOnly: false },
    { value: "u20", label: "Under 20%", eliteOnly: false },
    { value: "u25", label: "Under 25%", eliteOnly: false },
    { value: "u30", label: "Under 30%", eliteOnly: false },
    { value: "o5", label: "Over 5%", eliteOnly: false },
    { value: "o10", label: "Over 10%", eliteOnly: false },
    { value: "o15", label: "Over 15%", eliteOnly: false },
    { value: "o20", label: "Over 20%", eliteOnly: false },
    { value: "o25", label: "Over 25%", eliteOnly: false },
    { value: "o30", label: "Over 30%", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  analystRecom: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "strongbuy", label: "Strong Buy (1)", eliteOnly: false },
    { value: "buybetter", label: "Buy or better", eliteOnly: false },
    { value: "buy", label: "Buy", eliteOnly: false },
    { value: "holdbetter", label: "Hold or better", eliteOnly: false },
    { value: "hold", label: "Hold", eliteOnly: false },
    { value: "holdworse", label: "Hold or worse", eliteOnly: false },
    { value: "sell", label: "Sell", eliteOnly: false },
    { value: "sellworse", label: "Sell or worse", eliteOnly: false },
    { value: "strongsell", label: "Strong Sell (5)", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  optionShort: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "option", label: "Optionable", eliteOnly: false },
    { value: "short", label: "Shortable", eliteOnly: false },
    { value: "notoption", label: "Not optionable", eliteOnly: false },
    { value: "notshort", label: "Not shortable", eliteOnly: false },
    { value: "optionshort", label: "Optionable and shortable", eliteOnly: false },
    { value: "optionnotshort", label: "Optionable and not shortable", eliteOnly: false },
    { value: "notoptionshort", label: "Not optionable and shortable", eliteOnly: false },
    { value: "notoptionnotshort", label: "Not optionable and not shortable", eliteOnly: false },
    { value: "restricted", label: "Short Sale Restricted (Elite only)", eliteOnly: false },
    { value: "restricted", label: "Halted (Elite only)", eliteOnly: false },
    { value: "so10k", label: "Over 10K available to short", eliteOnly: false },
    { value: "so100k", label: "Over 100K available to short", eliteOnly: false },
    { value: "so1m", label: "Over 1M available to short", eliteOnly: false },
    { value: "so10m", label: "Over 10M available to short", eliteOnly: false },
    { value: "uo1m", label: "Over $1M available to short", eliteOnly: false },
    { value: "uo10m", label: "Over $10M available to short", eliteOnly: false },
    { value: "uo100m", label: "Over $100M available to short", eliteOnly: false },
    { value: "uo1b", label: "Over $1B available to short", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  earningsDate: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "today", label: "Today", eliteOnly: false },
    { value: "todaybefore", label: "Today Before Market Open", eliteOnly: false },
    { value: "todayafter", label: "Today After Market Close", eliteOnly: false },
    { value: "tomorrow", label: "Tomorrow", eliteOnly: false },
    { value: "tomorrowbefore", label: "Tomorrow Before Market Open", eliteOnly: false },
    { value: "tomorrowafter", label: "Tomorrow After Market Close", eliteOnly: false },
    { value: "yesterday", label: "Yesterday", eliteOnly: false },
    { value: "yesterdaybefore", label: "Yesterday Before Market Open", eliteOnly: false },
    { value: "yesterdayafter", label: "Yesterday After Market Close", eliteOnly: false },
    { value: "nextdays5", label: "Next 5 Days", eliteOnly: false },
    { value: "prevdays5", label: "Previous 5 Days", eliteOnly: false },
    { value: "thisweek", label: "This Week", eliteOnly: false },
    { value: "nextweek", label: "Next Week", eliteOnly: false },
    { value: "prevweek", label: "Previous Week", eliteOnly: false },
    { value: "thismonth", label: "This Month", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  avgVolume: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "u50", label: "Under 50K", eliteOnly: false },
    { value: "u100", label: "Under 100K", eliteOnly: false },
    { value: "u500", label: "Under 500K", eliteOnly: false },
    { value: "u750", label: "Under 750K", eliteOnly: false },
    { value: "u1000", label: "Under 1M", eliteOnly: false },
    { value: "o50", label: "Over 50K", eliteOnly: false },
    { value: "o100", label: "Over 100K", eliteOnly: false },
    { value: "o200", label: "Over 200K", eliteOnly: false },
    { value: "o300", label: "Over 300K", eliteOnly: false },
    { value: "o400", label: "Over 400K", eliteOnly: false },
    { value: "o500", label: "Over 500K", eliteOnly: false },
    { value: "o750", label: "Over 750K", eliteOnly: false },
    { value: "o1000", label: "Over 1M", eliteOnly: false },
    { value: "o2000", label: "Over 2M", eliteOnly: false },
    { value: "100to500", label: "100K to 500K", eliteOnly: false },
    { value: "100to1000", label: "100K to 1M", eliteOnly: false },
    { value: "500to1000", label: "500K to 1M", eliteOnly: false },
    { value: "500to10000", label: "500K to 10M", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  relVolume: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "o10", label: "Over 10", eliteOnly: false },
    { value: "o5", label: "Over 5", eliteOnly: false },
    { value: "o3", label: "Over 3", eliteOnly: false },
    { value: "o2", label: "Over 2", eliteOnly: false },
    { value: "o1.5", label: "Over 1.5", eliteOnly: false },
    { value: "o1", label: "Over 1", eliteOnly: false },
    { value: "o0.75", label: "Over 0.75", eliteOnly: false },
    { value: "o0.5", label: "Over 0.5", eliteOnly: false },
    { value: "o0.25", label: "Over 0.25", eliteOnly: false },
    { value: "u2", label: "Under 2", eliteOnly: false },
    { value: "u1.5", label: "Under 1.5", eliteOnly: false },
    { value: "u1", label: "Under 1", eliteOnly: false },
    { value: "u0.75", label: "Under 0.75", eliteOnly: false },
    { value: "u0.5", label: "Under 0.5", eliteOnly: false },
    { value: "u0.25", label: "Under 0.25", eliteOnly: false },
    { value: "u0.1", label: "Under 0.1", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  currentVolume: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "u50", label: "Under 50K", eliteOnly: false },
    { value: "u100", label: "Under 100K", eliteOnly: false },
    { value: "u500", label: "Under 500K", eliteOnly: false },
    { value: "u750", label: "Under 750K", eliteOnly: false },
    { value: "u1000", label: "Under 1M", eliteOnly: false },
    { value: "o0", label: "Over 0", eliteOnly: false },
    { value: "o50", label: "Over 50K", eliteOnly: false },
    { value: "o100", label: "Over 100K", eliteOnly: false },
    { value: "o200", label: "Over 200K", eliteOnly: false },
    { value: "o300", label: "Over 300K", eliteOnly: false },
    { value: "o400", label: "Over 400K", eliteOnly: false },
    { value: "o500", label: "Over 500K", eliteOnly: false },
    { value: "o750", label: "Over 750K", eliteOnly: false },
    { value: "o1000", label: "Over 1M", eliteOnly: false },
    { value: "o2000", label: "Over 2M", eliteOnly: false },
    { value: "o5000", label: "Over 5M", eliteOnly: false },
    { value: "o10000", label: "Over 10M", eliteOnly: false },
    { value: "o20000", label: "Over 20M", eliteOnly: false },
    { value: "o50sf", label: "Over 50% shares float", eliteOnly: false },
    { value: "o100sf", label: "Over 100% shares float", eliteOnly: false },
    { value: "uusd1000", label: "Under $1M", eliteOnly: false },
    { value: "uusd10000", label: "Under $10M", eliteOnly: false },
    { value: "uusd100000", label: "Under $100M", eliteOnly: false },
    { value: "uusd1000000", label: "Under $1B", eliteOnly: false },
    { value: "ousd1000", label: "Over $1M", eliteOnly: false },
    { value: "ousd10000", label: "Over $10M", eliteOnly: false },
    { value: "ousd100000", label: "Over $100M", eliteOnly: false },
    { value: "ousd1000000", label: "Over $1B", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  trades: [
    { value: "", label: "Elite only", eliteOnly: false },
  ],
  priceBand: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "u1", label: "Under $1", eliteOnly: false },
    { value: "u2", label: "Under $2", eliteOnly: false },
    { value: "u3", label: "Under $3", eliteOnly: false },
    { value: "u4", label: "Under $4", eliteOnly: false },
    { value: "u5", label: "Under $5", eliteOnly: false },
    { value: "u7", label: "Under $7", eliteOnly: false },
    { value: "u10", label: "Under $10", eliteOnly: false },
    { value: "u15", label: "Under $15", eliteOnly: false },
    { value: "u20", label: "Under $20", eliteOnly: false },
    { value: "u30", label: "Under $30", eliteOnly: false },
    { value: "u40", label: "Under $40", eliteOnly: false },
    { value: "u50", label: "Under $50", eliteOnly: false },
    { value: "o1", label: "Over $1", eliteOnly: false },
    { value: "o2", label: "Over $2", eliteOnly: false },
    { value: "o3", label: "Over $3", eliteOnly: false },
    { value: "o4", label: "Over $4", eliteOnly: false },
    { value: "o5", label: "Over $5", eliteOnly: false },
    { value: "o7", label: "Over $7", eliteOnly: false },
    { value: "o10", label: "Over $10", eliteOnly: false },
    { value: "o15", label: "Over $15", eliteOnly: false },
    { value: "o20", label: "Over $20", eliteOnly: false },
    { value: "o30", label: "Over $30", eliteOnly: false },
    { value: "o40", label: "Over $40", eliteOnly: false },
    { value: "o50", label: "Over $50", eliteOnly: false },
    { value: "o60", label: "Over $60", eliteOnly: false },
    { value: "o70", label: "Over $70", eliteOnly: false },
    { value: "o80", label: "Over $80", eliteOnly: false },
    { value: "o90", label: "Over $90", eliteOnly: false },
    { value: "o100", label: "Over $100", eliteOnly: false },
    { value: "1to5", label: "$1 to $5", eliteOnly: false },
    { value: "1to10", label: "$1 to $10", eliteOnly: false },
    { value: "1to20", label: "$1 to $20", eliteOnly: false },
    { value: "5to10", label: "$5 to $10", eliteOnly: false },
    { value: "5to20", label: "$5 to $20", eliteOnly: false },
    { value: "5to50", label: "$5 to $50", eliteOnly: false },
    { value: "10to20", label: "$10 to $20", eliteOnly: false },
    { value: "10to50", label: "$10 to $50", eliteOnly: false },
    { value: "20to50", label: "$20 to $50", eliteOnly: false },
    { value: "50to100", label: "$50 to $100", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
    { value: "add_tad_0_close::close:d", label: "Custom TA", eliteOnly: false },
  ],
  targetPrice: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "a50", label: "50% Above Price", eliteOnly: false },
    { value: "a40", label: "40% Above Price", eliteOnly: false },
    { value: "a30", label: "30% Above Price", eliteOnly: false },
    { value: "a20", label: "20% Above Price", eliteOnly: false },
    { value: "a10", label: "10% Above Price", eliteOnly: false },
    { value: "a5", label: "5% Above Price", eliteOnly: false },
    { value: "above", label: "Above Price", eliteOnly: false },
    { value: "below", label: "Below Price", eliteOnly: false },
    { value: "b5", label: "5% Below Price", eliteOnly: false },
    { value: "b10", label: "10% Below Price", eliteOnly: false },
    { value: "b20", label: "20% Below Price", eliteOnly: false },
    { value: "b30", label: "30% Below Price", eliteOnly: false },
    { value: "b40", label: "40% Below Price", eliteOnly: false },
    { value: "b50", label: "50% Below Price", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  ipoDate: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "today", label: "Today", eliteOnly: false },
    { value: "yesterday", label: "Yesterday", eliteOnly: false },
    { value: "prevweek", label: "In the last week", eliteOnly: false },
    { value: "prevmonth", label: "In the last month", eliteOnly: false },
    { value: "prevquarter", label: "In the last quarter", eliteOnly: false },
    { value: "prevyear", label: "In the last year", eliteOnly: false },
    { value: "prev2yrs", label: "In the last 2 years", eliteOnly: false },
    { value: "prev3yrs", label: "In the last 3 years", eliteOnly: false },
    { value: "prev5yrs", label: "In the last 5 years", eliteOnly: false },
    { value: "more1", label: "More than a year ago", eliteOnly: false },
    { value: "more5", label: "More than 5 years ago", eliteOnly: false },
    { value: "more10", label: "More than 10 years ago", eliteOnly: false },
    { value: "more15", label: "More than 15 years ago", eliteOnly: false },
    { value: "more20", label: "More than 20 years ago", eliteOnly: false },
    { value: "more25", label: "More than 25 years ago", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  sharesOutstanding: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "u1", label: "Under 1M", eliteOnly: false },
    { value: "u5", label: "Under 5M", eliteOnly: false },
    { value: "u10", label: "Under 10M", eliteOnly: false },
    { value: "u20", label: "Under 20M", eliteOnly: false },
    { value: "u50", label: "Under 50M", eliteOnly: false },
    { value: "u100", label: "Under 100M", eliteOnly: false },
    { value: "o1", label: "Over 1M", eliteOnly: false },
    { value: "o2", label: "Over 2M", eliteOnly: false },
    { value: "o5", label: "Over 5M", eliteOnly: false },
    { value: "o10", label: "Over 10M", eliteOnly: false },
    { value: "o20", label: "Over 20M", eliteOnly: false },
    { value: "o50", label: "Over 50M", eliteOnly: false },
    { value: "o100", label: "Over 100M", eliteOnly: false },
    { value: "o200", label: "Over 200M", eliteOnly: false },
    { value: "o500", label: "Over 500M", eliteOnly: false },
    { value: "o1000", label: "Over 1000M", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  float: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "u1", label: "Under 1M", eliteOnly: false },
    { value: "u5", label: "Under 5M", eliteOnly: false },
    { value: "u10", label: "Under 10M", eliteOnly: false },
    { value: "u20", label: "Under 20M", eliteOnly: false },
    { value: "u50", label: "Under 50M", eliteOnly: false },
    { value: "u100", label: "Under 100M", eliteOnly: false },
    { value: "o1", label: "Over 1M", eliteOnly: false },
    { value: "o2", label: "Over 2M", eliteOnly: false },
    { value: "o5", label: "Over 5M", eliteOnly: false },
    { value: "o10", label: "Over 10M", eliteOnly: false },
    { value: "o20", label: "Over 20M", eliteOnly: false },
    { value: "o50", label: "Over 50M", eliteOnly: false },
    { value: "o100", label: "Over 100M", eliteOnly: false },
    { value: "o200", label: "Over 200M", eliteOnly: false },
    { value: "o500", label: "Over 500M", eliteOnly: false },
    { value: "o1000", label: "Over 1000M", eliteOnly: false },
    { value: "u10p", label: "Under 10%", eliteOnly: false },
    { value: "u20p", label: "Under 20%", eliteOnly: false },
    { value: "u30p", label: "Under 30%", eliteOnly: false },
    { value: "u40p", label: "Under 40%", eliteOnly: false },
    { value: "u50p", label: "Under 50%", eliteOnly: false },
    { value: "u60p", label: "Under 60%", eliteOnly: false },
    { value: "u70p", label: "Under 70%", eliteOnly: false },
    { value: "u80p", label: "Under 80%", eliteOnly: false },
    { value: "u90p", label: "Under 90%", eliteOnly: false },
    { value: "o10p", label: "Over 10%", eliteOnly: false },
    { value: "o20p", label: "Over 20%", eliteOnly: false },
    { value: "o30p", label: "Over 30%", eliteOnly: false },
    { value: "o40p", label: "Over 40%", eliteOnly: false },
    { value: "o50p", label: "Over 50%", eliteOnly: false },
    { value: "o60p", label: "Over 60%", eliteOnly: false },
    { value: "o70p", label: "Over 70%", eliteOnly: false },
    { value: "o80p", label: "Over 80%", eliteOnly: false },
    { value: "o90p", label: "Over 90%", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  theme: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "agingpopulationlongevity", label: "Aging Population & Longevity", eliteOnly: false },
    { value: "agriculturefoodtech", label: "Agriculture & FoodTech", eliteOnly: false },
    { value: "artificialintelligence", label: "Artificial Intelligence", eliteOnly: false },
    { value: "autonomoussystems", label: "Autonomous Systems", eliteOnly: false },
    { value: "bigdata", label: "Big Data", eliteOnly: false },
    { value: "biometrics", label: "Biometrics", eliteOnly: false },
    { value: "cloudcomputing", label: "Cloud Computing", eliteOnly: false },
    { value: "commoditiesagriculture", label: "Commodities - Agriculture", eliteOnly: false },
    { value: "commoditiesenergy", label: "Commodities - Energy", eliteOnly: false },
    { value: "commoditiesmetals", label: "Commodities - Metals", eliteOnly: false },
    { value: "consumergoods", label: "Consumer Goods", eliteOnly: false },
    { value: "cryptoblockchain", label: "Crypto & Blockchain", eliteOnly: false },
    { value: "cybersecurity", label: "Cybersecurity", eliteOnly: false },
    { value: "defenseaerospace", label: "Defense & Aerospace", eliteOnly: false },
    { value: "digitalentertainment", label: "Digital Entertainment", eliteOnly: false },
    { value: "ecommerce", label: "E-commerce", eliteOnly: false },
    { value: "educationtechnology", label: "Education Technology", eliteOnly: false },
    { value: "electricvehicles", label: "Electric Vehicles", eliteOnly: false },
    { value: "energyrenewable", label: "Energy - Renewable", eliteOnly: false },
    { value: "energytraditional", label: "Energy - Traditional", eliteOnly: false },
    { value: "environmentalsustainability", label: "Environmental Sustainability", eliteOnly: false },
    { value: "fintech", label: "FinTech", eliteOnly: false },
    { value: "hardware", label: "Hardware", eliteOnly: false },
    { value: "healthcarebiotech", label: "Healthcare & Biotech", eliteOnly: false },
    { value: "healthyfoodnutrition", label: "Healthy Food & Nutrition", eliteOnly: false },
    { value: "industrialautomation", label: "Industrial Automation", eliteOnly: false },
    { value: "internetofthings", label: "Internet of Things", eliteOnly: false },
    { value: "nanotechnology", label: "Nanotechnology", eliteOnly: false },
    { value: "quantumcomputing", label: "Quantum Computing", eliteOnly: false },
    { value: "realestatereits", label: "Real Estate & REITs", eliteOnly: false },
    { value: "robotics", label: "Robotics", eliteOnly: false },
    { value: "semiconductors", label: "Semiconductors", eliteOnly: false },
    { value: "smarthome", label: "Smart Home", eliteOnly: false },
    { value: "socialmedia", label: "Social Media", eliteOnly: false },
    { value: "software", label: "Software", eliteOnly: false },
    { value: "spacetech", label: "Space Tech", eliteOnly: false },
    { value: "telecommunications", label: "Telecommunications", eliteOnly: false },
    { value: "transportationlogistics", label: "Transportation & Logistics", eliteOnly: false },
    { value: "virtualaugmentedreality", label: "Virtual & Augmented Reality", eliteOnly: false },
    { value: "wearables", label: "Wearables", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
  subTheme: [
    { value: "", label: "Any", eliteOnly: false },
    { value: "agriculturealtprotein", label: "Agriculture - Alternative Proteins", eliteOnly: false },
    { value: "agriculturecropinputs", label: "Agriculture - Agricultural Inputs & Crop Science", eliteOnly: false },
    { value: "agricultureindoorfarming", label: "Agriculture - Controlled Environment Agriculture", eliteOnly: false },
    { value: "agricultureprocessing", label: "Agriculture - Agri-Food Processing & Distribution", eliteOnly: false },
    { value: "agriculturesmartfarming", label: "Agriculture - Precision Agriculture & Farm Automation", eliteOnly: false },
    { value: "aiadssearch", label: "AI - Ads, Search & Recommendations", eliteOnly: false },
    { value: "aiagi", label: "AI - AGI, general intelligence", eliteOnly: false },
    { value: "aiapplications", label: "AI - Apps, Domain-Specific AI", eliteOnly: false },
    { value: "aicloud", label: "AI - Cloud & Infrastructure", eliteOnly: false },
    { value: "aicompute", label: "AI - Compute & Acceleration", eliteOnly: false },
    { value: "aidata", label: "AI - Data Infrastructure & Enablement", eliteOnly: false },
    { value: "aiedge", label: "AI - Edge & Embedded Systems", eliteOnly: false },
    { value: "aienergy", label: "AI - Power & Energy Solutions", eliteOnly: false },
    { value: "aienterprise", label: "AI - Enterprise Productivity & Software Integration", eliteOnly: false },
    { value: "aimodels", label: "AI - Foundation Models & Platforms", eliteOnly: false },
    { value: "ainetworking", label: "AI - Networking & Systems Optimization", eliteOnly: false },
    { value: "airobotics", label: "AI - Robotics & Automation", eliteOnly: false },
    { value: "aisecurity", label: "AI - Cybersecurity", eliteOnly: false },
    { value: "automationautomation", label: "Automation - Factory & Process Automation Systems", eliteOnly: false },
    { value: "automationdprinting", label: "Automation - Additive Manufacturing, 3D Printing", eliteOnly: false },
    { value: "automationiot", label: "Automation - Industrial IoT, Connectivity", eliteOnly: false },
    { value: "automationlogistics", label: "Automation - Smart Logistics & Warehouse Automation", eliteOnly: false },
    { value: "automationmachinevision", label: "Automation - Industrial Sensors & Machine Vision", eliteOnly: false },
    { value: "automationrobotics", label: "Automation - Industrial Robotics & Autonomous Systems", eliteOnly: false },
    { value: "automationsoftware", label: "Automation - Industrial Software & Digital Twin", eliteOnly: false },
    { value: "autonomousavmobility", label: "Autonomous  - Vehicles & Mobility", eliteOnly: false },
    { value: "autonomousdefense", label: "Autonomous  - Aerospace, Defense & Drones", eliteOnly: false },
    { value: "autonomousindustrial", label: "Autonomous  - Industrial & Logistics Automation", eliteOnly: false },
    { value: "autonomousmachinevision", label: "Autonomous  - Sensors & Perception Systems", eliteOnly: false },
    { value: "autonomoussoftware", label: "Autonomous  - Software & Cloud Infrastructure", eliteOnly: false },
    { value: "autonomousspecialized", label: "Autonomous  - Maritime, Agriculture & Specialized Autonomy", eliteOnly: false },
    { value: "bigdataaiplatforms", label: "Big Data - AI Platforms & Predictive Analytics", eliteOnly: false },
    { value: "bigdataanalyticsbi", label: "Big Data - Analytics & Business Intelligence", eliteOnly: false },
    { value: "bigdatainfrastructure", label: "Big Data - Infrastructure & Storage", eliteOnly: false },
    { value: "bigdataproviders", label: "Big Data - Data Generation, Sourcing & Providers", eliteOnly: false },
    { value: "biometricsgovdefense", label: "Biometrics - Government, Defense & Public Security", eliteOnly: false },
    { value: "biometricshardware", label: "Biometrics - Biometric Sensors & Hardware", eliteOnly: false },
    { value: "biometricsidentity", label: "Biometrics - Identity Verification & Security", eliteOnly: false },
    { value: "biometricssoftware", label: "Biometrics - Recognition & Analytics", eliteOnly: false },
    { value: "blockchainenterprise", label: "Blockchain - Enterprise Blockchain Solutions", eliteOnly: false },
    { value: "blockchaininfrastructure", label: "Blockchain - Blockchain Infrastructure", eliteOnly: false },
    { value: "blockchainmining", label: "Blockchain - Cryptocurrency Mining & Staking", eliteOnly: false },
    { value: "blockchainpayments", label: "Blockchain - Financial Services & Payments", eliteOnly: false },
    { value: "blockchainplatforms", label: "Blockchain - Cryptocurrency Platforms", eliteOnly: false },
    { value: "blockchaintokenization", label: "Blockchain - Tokenization & Digital Assets", eliteOnly: false },
    { value: "clouddatabases", label: "Cloud - Data Platforms & Databases", eliteOnly: false },
    { value: "clouddatacenters", label: "Cloud - Data Centers", eliteOnly: false },
    { value: "clouddevops", label: "Cloud - DevOps, Observability", eliteOnly: false },
    { value: "cloudedge", label: "Cloud - Edge, CDN, Zero-Trust Networking", eliteOnly: false },
    { value: "cloudhardware", label: "Cloud - Hardware, Networking & OEM", eliteOnly: false },
    { value: "cloudhsaas", label: "Cloud - Horizontal SaaS & Cloud Applications", eliteOnly: false },
    { value: "cloudhybridcloud", label: "Cloud - Hybrid Cloud", eliteOnly: false },
    { value: "cloudhyperscalers", label: "Cloud - Hyperscalers", eliteOnly: false },
    { value: "cloudmulticloud", label: "Cloud - Multi-Cloud Management", eliteOnly: false },
    { value: "cloudpaas", label: "Cloud - Platforms & Services, PaaS", eliteOnly: false },
    { value: "cloudsecurity", label: "Cloud - Security", eliteOnly: false },
    { value: "cloudserverless", label: "Cloud - Serverless Computing", eliteOnly: false },
    { value: "commagribiofuels", label: "Comm Agri - Renewable Fuels & Biofuels", eliteOnly: false },
    { value: "commagrifertilizers", label: "Comm Agri - Fertilizers, Crop Inputs & Seeds", eliteOnly: false },
    { value: "commagrigrains", label: "Comm Agri - Grains & Oilseeds", eliteOnly: false },
    { value: "commagrilivestock", label: "Comm Agri - Livestock & Animal Protein", eliteOnly: false },
    { value: "commagrisofts", label: "Comm Agri - Softs & Plantation Crops", eliteOnly: false },
    { value: "commenergybiofuels", label: "Comm Energy - Biofuels & Renewable Fuels", eliteOnly: false },
    { value: "commenergygaslng", label: "Comm Energy - Natural Gas & LNG", eliteOnly: false },
    { value: "commenergyoil", label: "Comm Energy - Crude Oil", eliteOnly: false },
    { value: "commenergyuranium", label: "Comm Energy - Uranium & Nuclear Fuels", eliteOnly: false },
    { value: "commmetalsbattery", label: "Comm Metals - Battery & Energy Transition Metals", eliteOnly: false },
    { value: "commmetalsgold", label: "Comm Metals - Gold", eliteOnly: false },
    { value: "commmetalsindustrial", label: "Comm Metals - Industrial & Base Metals", eliteOnly: false },
    { value: "commmetalsprecious", label: "Comm Metals - Precious Metals", eliteOnly: false },
    { value: "commmetalsrareearth", label: "Comm Metals - Rare Earth & Strategic Materials", eliteOnly: false },
    { value: "commmetalsrecycling", label: "Comm Metals - Recycling & Circular Materials", eliteOnly: false },
    { value: "commmetalssilver", label: "Comm Metals - Silver", eliteOnly: false },
    { value: "consumerapparel", label: "Consumer - Apparel & E-Commerce Retail", eliteOnly: false },
    { value: "consumerfarmdirect", label: "Consumer - Farming & Direct Marketplaces", eliteOnly: false },
    { value: "consumerfood", label: "Consumer - Health, Food & Beverages", eliteOnly: false },
    { value: "consumerhousehold", label: "Consumer - Smart Homes & Household Products", eliteOnly: false },
    { value: "consumerluxury", label: "Consumer - Modern Luxury & Lifestyle", eliteOnly: false },
    { value: "consumersecondhand", label: "Consumer - Resale & Sharing Platforms", eliteOnly: false },
    { value: "cybersecurityappsecurity", label: "Cybersecurity - Application Security", eliteOnly: false },
    { value: "cybersecuritycloud", label: "Cybersecurity - Cloud Security", eliteOnly: false },
    { value: "cybersecurityendpoint", label: "Cybersecurity - Endpoint Security", eliteOnly: false },
    { value: "cybersecurityidentityiam", label: "Cybersecurity - Identity & Access Management", eliteOnly: false },
    { value: "cybersecuritynetwork", label: "Cybersecurity - Network Security", eliteOnly: false },
    { value: "cybersecuritysiem", label: "Cybersecurity - Security Information & Event Management", eliteOnly: false },
    { value: "cybersecuritythreatops", label: "Cybersecurity - Threat Intelligence", eliteOnly: false },
    { value: "cybersecurityzerotrust", label: "Cybersecurity - Zero Trust", eliteOnly: false },
    { value: "defenseaviation", label: "Defense - Next-Generation Aircraft & Maintenance", eliteOnly: false },
    { value: "defensecyberdefense", label: "Defense - Cyber Defense & Electronic Warfare", eliteOnly: false },
    { value: "defensedrones", label: "Defense - Drones & Anti-Drone Systems", eliteOnly: false },
    { value: "defensemanufacturing", label: "Defense - Secure Defense Supply Chains", eliteOnly: false },
    { value: "defensemissiles", label: "Defense - Missile Defense & Long-Range Weapons", eliteOnly: false },
    { value: "defensespacetech", label: "Defense - Space Technology & Satellite Services", eliteOnly: false },
    { value: "defenseweapons", label: "Defense - Precision Weapons & Ammunition Resupply", eliteOnly: false },
    { value: "ecommerceadsmedia", label: "E-commerce - Retail Media & Advertising", eliteOnly: false },
    { value: "ecommercedtc", label: "E-commerce - Direct-to-Consumer", eliteOnly: false },
    { value: "ecommercegrocery", label: "E-commerce - Grocery & Local Commerce Platforms", eliteOnly: false },
    { value: "ecommercelogistics", label: "E-commerce - Logistics & Delivery", eliteOnly: false },
    { value: "ecommercemarketplaces", label: "E-commerce - Online Marketplaces", eliteOnly: false },
    { value: "ecommerceomnichannel", label: "E-commerce - Omnichannel Retailers, Online & Physical Stores", eliteOnly: false },
    { value: "ecommerceplatforms", label: "E-commerce - Platforms", eliteOnly: false },
    { value: "ecommercesecondhand", label: "E-commerce - Recommerce, Secondhand Marketplaces", eliteOnly: false },
    { value: "ecommercesocial", label: "E-commerce - Social & Influencer Commerce", eliteOnly: false },
    { value: "educationcurriculum", label: "Education - Digital Curriculum", eliteOnly: false },
    { value: "educationinfrastructure", label: "Education - Infrastructure", eliteOnly: false },
    { value: "educationplatforms", label: "Education - Online Learning Platforms", eliteOnly: false },
    { value: "educationworkforce", label: "Education - Workforce Training", eliteOnly: false },
    { value: "energybasemajors", label: "Energy Base - Integrated Energy Majors", eliteOnly: false },
    { value: "energybasenuclear", label: "Energy Base - Nuclear Power & Advanced Reactors", eliteOnly: false },
    { value: "energybaseoilproduction", label: "Energy Base - Oil & Gas Exploration & Production", eliteOnly: false },
    { value: "energybaseoilrefining", label: "Energy Base - Refining & Midstream Infrastructure", eliteOnly: false },
    { value: "energybaseoilservices", label: "Energy Base - Oilfield Services & Equipment", eliteOnly: false },
    { value: "energybasethermal", label: "Energy Base - Coal & Thermal Power Generation", eliteOnly: false },
    { value: "energybaseutilities", label: "Energy Base - Utilities & Conventional Power Operators", eliteOnly: false },
    { value: "energycleanbatteries", label: "Energy Clean - Batteries & Storage", eliteOnly: false },
    { value: "energycleanbiofuels", label: "Energy Clean - Fuels & Bioenergy", eliteOnly: false },
    { value: "energycleangeothermal", label: "Energy Clean - Geothermal", eliteOnly: false },
    { value: "energycleanhydrogen", label: "Energy Clean - Hydrogen & Fuel Cells", eliteOnly: false },
    { value: "energycleanmaterials", label: "Energy Clean - Materials & Critical Metals", eliteOnly: false },
    { value: "energycleansmartgrid", label: "Energy Clean - Smart Grid & Electrification", eliteOnly: false },
    { value: "energycleansolar", label: "Energy Clean - Solar", eliteOnly: false },
    { value: "energycleanutilities", label: "Energy Clean - Utilities & Clean Power Operators", eliteOnly: false },
    { value: "energycleanwind", label: "Energy Clean - Wind", eliteOnly: false },
    { value: "entertainmentbetting", label: "Entertainment - Sports Betting, Wagering & Prediction Markets", eliteOnly: false },
    { value: "entertainmentgambling", label: "Entertainment - iGaming & Online Gambling", eliteOnly: false },
    { value: "entertainmentgaming", label: "Entertainment - Game Publishers & Developers", eliteOnly: false },
    { value: "entertainmentinfrastructure", label: "Entertainment - Streaming & Gaming Infrastructure", eliteOnly: false },
    { value: "entertainmentmusic", label: "Entertainment - Music & Audio Streaming", eliteOnly: false },
    { value: "entertainmentvideo", label: "Entertainment - Video Streaming", eliteOnly: false },
    { value: "environmentalagriculture", label: "Environmental - Sustainable Agriculture & Resource Management", eliteOnly: false },
    { value: "environmentalairquality", label: "Environmental - Clean Technologies & Pollution Control", eliteOnly: false },
    { value: "environmentalclimate", label: "Environmental - Climate Technologies & Carbon Solutions", eliteOnly: false },
    { value: "environmentalwaste", label: "Environmental - Waste Management & Recycling", eliteOnly: false },
    { value: "environmentalwater", label: "Environmental - Water Infrastructure & Treatment", eliteOnly: false },
    { value: "evsbatteries", label: "EVs - Batteries & Materials", eliteOnly: false },
    { value: "evscharging", label: "EVs - Charging & Infrastructure", eliteOnly: false },
    { value: "evschips", label: "EVs - Auto Semiconductors & Power Electronics", eliteOnly: false },
    { value: "evsfleets", label: "EVs - Fleet Management & Telematics", eliteOnly: false },
    { value: "evsmanufacturers", label: "EVs - Manufacturers", eliteOnly: false },
    { value: "evsselfdriving", label: "EVs - Autonomous Driving", eliteOnly: false },
    { value: "evssuppliers", label: "EVs - Key Suppliers & Autonomy Tech", eliteOnly: false },
    { value: "fintechblockchain", label: "FinTech - Crypto, Blockchain & Tokenization", eliteOnly: false },
    { value: "fintechexchanges", label: "FinTech - Exchanges & Market Infrastructure", eliteOnly: false },
    { value: "fintechinsurance", label: "FinTech - InsurTech & Embedded Insurance", eliteOnly: false },
    { value: "fintechlending", label: "FinTech - Lending, Credit & BNPL", eliteOnly: false },
    { value: "fintechneobanks", label: "FinTech - Digital Banking & Neobanks", eliteOnly: false },
    { value: "fintechpayments", label: "FinTech - Digital Payments & Merchant Infrastructure", eliteOnly: false },
    { value: "fintechtrading", label: "FinTech - Trading Platforms & WealthTech", eliteOnly: false },
    { value: "hardwaredatacenters", label: "Hardware - Data Center Infrastructure", eliteOnly: false },
    { value: "hardwareelectronics", label: "Hardware - Consumer Electronics, Gaming PCs & Consoles", eliteOnly: false },
    { value: "hardwaregaming", label: "Hardware - Gaming & Immersive Pheriperals", eliteOnly: false },
    { value: "hardwareindustrialiot", label: "Hardware - Industrial & IoT", eliteOnly: false },
    { value: "hardwarenetworking", label: "Hardware - Networking Equipment", eliteOnly: false },
    { value: "hardwarenextgen", label: "Hardware - Next-Gen & Specialty", eliteOnly: false },
    { value: "hardwarepcsdevices", label: "Hardware - Personal Computing & Devices", eliteOnly: false },
    { value: "hardwareprinting", label: "Hardware - Printing & Imaging", eliteOnly: false },
    { value: "hardwareservers", label: "Hardware - Servers, OEMs & Enterprise Systems", eliteOnly: false },
    { value: "hardwarestorage", label: "Hardware - Storage", eliteOnly: false },
    { value: "hardwaretelecom", label: "Hardware - Communications & Telecom", eliteOnly: false },
    { value: "healthcaredevices", label: "Healthcare - Medical Devices & HealthTech Hardware", eliteOnly: false },
    { value: "healthcarediagnostics", label: "Healthcare - Diagnostics, Biomarkers & Liquid Biopsy", eliteOnly: false },
    { value: "healthcaregenomics", label: "Healthcare - Genomics & Personalized Medicine", eliteOnly: false },
    { value: "healthcareitdata", label: "Healthcare - IT, Services & Data Infrastructure", eliteOnly: false },
    { value: "healthcaremetabolic", label: "Healthcare - Metabolic & Cardiometabolic", eliteOnly: false },
    { value: "healthcarenextgen", label: "Healthcare - Next-Gen Biotech Platforms", eliteOnly: false },
    { value: "healthcareoncology", label: "Healthcare - Oncology & Precision Cancer Therapeutics", eliteOnly: false },
    { value: "healthcaretelemedicine", label: "Healthcare - Digital Health, Telemedicine & Remote Care", eliteOnly: false },
    { value: "healthcaretherapeutics", label: "Healthcare - Regenerative Medicine, Psychedelics, Cannabis", eliteOnly: false },
    { value: "iotedgedevices", label: "IoT - Connected Devices & Sensors", eliteOnly: false },
    { value: "iotenterprise", label: "IoT - Industrial & Enterprise IoT", eliteOnly: false },
    { value: "iothardware", label: "IoT - Edge Computing & Hardware Infrastructure", eliteOnly: false },
    { value: "iotnetworking", label: "IoT - Connectivity & Networks", eliteOnly: false },
    { value: "iotsecurity", label: "IoT - Security & Data Management", eliteOnly: false },
    { value: "iotsoftware", label: "IoT - Platforms, Software & Analytics", eliteOnly: false },
    { value: "longevityagingpharma", label: "Longevity - Age-Related Pharmaceuticals & Biotech", eliteOnly: false },
    { value: "longevityhealthcare", label: "Longevity - Healthcare & Medical Devices", eliteOnly: false },
    { value: "longevityhealthyaging", label: "Longevity - Healthy Aging & Nutrition", eliteOnly: false },
    { value: "longevityseniorliving", label: "Longevity - Senior Living & Assisted Care", eliteOnly: false },
    { value: "nanotechelectronics", label: "NanoTech - Nanoelectronics & Semiconductors", eliteOnly: false },
    { value: "nanotechenergy", label: "NanoTech - Energy & Environment", eliteOnly: false },
    { value: "nanotechmaterials", label: "NanoTech - Nanomaterials & Manufacturing", eliteOnly: false },
    { value: "nanotechmedicine", label: "NanoTech - Nanomedicine & Drug Delivery", eliteOnly: false },
    { value: "nanotechproducts", label: "NanoTech - Consumer & Industrial Products", eliteOnly: false },
    { value: "nanotechresearchtools", label: "NanoTech - Research Tools & Advanced Instruments", eliteOnly: false },
    { value: "nutritionaltprotein", label: "Nutrition - Plant-Based Foods & Meat Alternatives", eliteOnly: false },
    { value: "nutritionmealdelivery", label: "Nutrition - Food Delivery & Meal Kits", eliteOnly: false },
    { value: "nutritionretailers", label: "Nutrition - Organic & Natural Food Retailers", eliteOnly: false },
    { value: "nutritionsupplements", label: "Nutrition - Functional & Nutritional Supplements", eliteOnly: false },
    { value: "quantumapplications", label: "Quantum  - Applications", eliteOnly: false },
    { value: "quantumcloud", label: "Quantum  - Cloud Ecosystems", eliteOnly: false },
    { value: "quantumenablingtech", label: "Quantum  - Enabling Technologies", eliteOnly: false },
    { value: "quantumhardware", label: "Quantum  - Hardware Platforms", eliteOnly: false },
    { value: "quantumnetworking", label: "Quantum  - Networking & Security", eliteOnly: false },
    { value: "quantumsoftware", label: "Quantum  - Software & Tools", eliteOnly: false },
    { value: "realestatehealthcare", label: "Real Estate - Healthcare & Senior Living", eliteOnly: false },
    { value: "realestatehousing", label: "Real Estate - Housing, Urban Living & Demographics", eliteOnly: false },
    { value: "realestateittelecom", label: "Real Estate - Digital Infrastructure", eliteOnly: false },
    { value: "realestateoffice", label: "Real Estate - Office & Commercial Workspaces", eliteOnly: false },
    { value: "realestateretail", label: "Real Estate - Retail & Consumer Real Estate", eliteOnly: false },
    { value: "realestatetourism", label: "Real Estate - Travel, Leisure & Entertainment Properties", eliteOnly: false },
    { value: "realestatewarehousing", label: "Real Estate - E-Commerce, Warehousing & Logistics", eliteOnly: false },
    { value: "roboticsautomation", label: "Robotics - Industrial Automation", eliteOnly: false },
    { value: "roboticsavmobility", label: "Robotics - Autonomous Vehicles & Mobility", eliteOnly: false },
    { value: "roboticsconsumer", label: "Robotics - Service & Consumer Robotics", eliteOnly: false },
    { value: "roboticslogistics", label: "Robotics - Logistics & Warehouse Robotics", eliteOnly: false },
    { value: "roboticsmachinevision", label: "Robotics - Sensors & Vision Systems", eliteOnly: false },
    { value: "roboticsmedical", label: "Robotics - Medical & Surgical Robotics", eliteOnly: false },
    { value: "semisanalog", label: "Semis - Analog, Mixed-Signal & Power Management", eliteOnly: false },
    { value: "semiscompute", label: "Semis - Logic & CPUs, GPUs, Accelerators", eliteOnly: false },
    { value: "semisdesigntools", label: "Semis - EDA Tools & Design Software", eliteOnly: false },
    { value: "semisfoundries", label: "Semis - Foundries & Manufacturing", eliteOnly: false },
    { value: "semislithography", label: "Semis - Equipment, Lithography & Deposition", eliteOnly: false },
    { value: "semismemory", label: "Semis - Memory & Storage", eliteOnly: false },
    { value: "semisnextgen", label: "Semis - Emerging Technologies", eliteOnly: false },
    { value: "semispackaging", label: "Semis - Testing, Packaging & Assembly", eliteOnly: false },
    { value: "semiswireless", label: "Semis - Wireless & Connectivity", eliteOnly: false },
    { value: "smarthomeautomation", label: "Smart Home - Automation & Control Systems", eliteOnly: false },
    { value: "smarthomedevices", label: "Smart Home - Connected Devices & Appliances", eliteOnly: false },
    { value: "smarthomeenergy", label: "Smart Home - Energy & Utilities", eliteOnly: false },
    { value: "smarthomenetworking", label: "Smart Home - Connectivity & Networking", eliteOnly: false },
    { value: "smarthomesecurity", label: "Smart Home - Security & Monitoring", eliteOnly: false },
    { value: "smarthomevoiceai", label: "Smart Home - Voice Assistants & AI Integration", eliteOnly: false },
    { value: "socialadvertising", label: "Social - Advertising Platforms", eliteOnly: false },
    { value: "socialgaming", label: "Social - Gaming Platforms", eliteOnly: false },
    { value: "socialnetworks", label: "Social - Networks & Communication Platforms", eliteOnly: false },
    { value: "socialniche", label: "Social - Niche Platforms", eliteOnly: false },
    { value: "socialvisualcontent", label: "Social - Image & Video Content Platforms", eliteOnly: false },
    { value: "softwarecollaboration", label: "Software - Collaboration & Communications", eliteOnly: false },
    { value: "softwarecrm", label: "Software - Customer Relationship Management & Marketing", eliteOnly: false },
    { value: "softwaredataanalytics", label: "Software - Data & Analytics", eliteOnly: false },
    { value: "softwaredesign", label: "Software - Design, Creativity & Engineering", eliteOnly: false },
    { value: "softwaredevops", label: "Software - DevOps, Management & Observability", eliteOnly: false },
    { value: "softwareecommerce", label: "Software - E-Commerce & Digital Platforms", eliteOnly: false },
    { value: "softwareenterprise", label: "Software - Enterprise Resource Planning & Management", eliteOnly: false },
    { value: "softwaregaming", label: "Software - Gaming & Platforms", eliteOnly: false },
    { value: "softwarehsaas", label: "Software - Horizontal SaaS Platforms", eliteOnly: false },
    { value: "softwareos", label: "Software - Operating Systems", eliteOnly: false },
    { value: "softwaresecurity", label: "Software - Cybersecurity", eliteOnly: false },
    { value: "softwarevsaas", label: "Software - Vertical SaaS Platforms", eliteOnly: false },
    { value: "spacedataanalytics", label: "Space - Data Analytics & Earth Observation", eliteOnly: false },
    { value: "spacedefense", label: "Space - Defense & Cybersecurity", eliteOnly: false },
    { value: "spaceinfrastructure", label: "Space - Infrastructure & Exploration", eliteOnly: false },
    { value: "spacelaunch", label: "Space - Logistics & Launch Services", eliteOnly: false },
    { value: "spacesatellites", label: "Space - Satellite Networks & Connectivity", eliteOnly: false },
    { value: "telecomcloudedge", label: "Telecom - Cloud & Edge Connectivity", eliteOnly: false },
    { value: "telecomenterprise", label: "Telecom - Enterprise & Unified Communications", eliteOnly: false },
    { value: "telecomg", label: "Telecom - 5G Technology & Semiconductors", eliteOnly: false },
    { value: "telecominfrastructure", label: "Telecom - Infrastructure & Equipment", eliteOnly: false },
    { value: "telecomsatcom", label: "Telecom - Satellite & Space Communication", eliteOnly: false },
    { value: "telecomwireless", label: "Telecom - Wireless Networks & Carriers", eliteOnly: false },
    { value: "transportationaircargo", label: "Transportation - Air Freight & Express Delivery", eliteOnly: false },
    { value: "transportationairtravel", label: "Transportation - Air Travel & Passenger Transportation", eliteOnly: false },
    { value: "transportationinfrastructure", label: "Transportation - Infrastructure & Equipment", eliteOnly: false },
    { value: "transportationmaritime", label: "Transportation - Marine Shipping & Ports", eliteOnly: false },
    { value: "transportationnextgen", label: "Transportation - Urban Mobility & Emerging Transport Tech", eliteOnly: false },
    { value: "transportationrail", label: "Transportation - Freight Rail & Infrastructure", eliteOnly: false },
    { value: "transportationtrucking", label: "Transportation - Trucking, LTL & Ground Freight", eliteOnly: false },
    { value: "transportationwarehousing", label: "Transportation - Logistics, Warehousing & Supply Chain Solutions", eliteOnly: false },
    { value: "varealityapplications", label: "V/A Reality - Content & Applications", eliteOnly: false },
    { value: "varealityenterprise", label: "V/A Reality - Enterprise & Industrial Solutions", eliteOnly: false },
    { value: "varealityhardware", label: "V/A Reality - Headsets & Hardware", eliteOnly: false },
    { value: "varealityinfrastructure", label: "V/A Reality - Infrastructure & Cloud Rendering", eliteOnly: false },
    { value: "varealitysoftware", label: "V/A Reality - Software Platforms & Operating Systems", eliteOnly: false },
    { value: "wearablesimmersive", label: "Wearables - Audio-Visual Immersive Devices", eliteOnly: false },
    { value: "wearablesmedical", label: "Wearables - Health Monitoring & Medical Devices", eliteOnly: false },
    { value: "wearablessmartwatches", label: "Wearables - Smartwatches & Fitness Devices", eliteOnly: false },
    { value: "wearablessoftware", label: "Wearables - Software & Ecosystems", eliteOnly: false },
    { value: "wearablessport", label: "Wearables - Sports, Fitness & Lifestyle Applications", eliteOnly: false },
    { value: "custom_subscription", label: "Custom (Elite only)", eliteOnly: true },
  ],
};
