version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 418384447921.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building bridge image...
      - cd bridge
      - docker build -t gualaloom-bridge .
      - docker tag gualaloom-bridge:latest ${IMAGE_URI}
      - docker tag gualaloom-bridge:latest 418384447921.dkr.ecr.us-east-1.amazonaws.com/gualaloom-bridge:latest
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push ${IMAGE_URI}
      - docker push 418384447921.dkr.ecr.us-east-1.amazonaws.com/gualaloom-bridge:latest
      - echo Done.
