"""Falsify or advance an exact causal projective hearing profile.

The candidate is the smallest exact physical basin suggested by linear
acoustic gain and superposition.  A causally authenticated THING owns the
positive rational cone generated by its complete bilateral full-field
trajectories.  This probe first tests the larger rational linear span.  If a
query is outside that span, it is necessarily outside the positive cone.

No distance, score, threshold, nearest relation, label-derived feature,
alignment, interpolation, or whole-root equality is used.  A non-membership
result carries a finite-field rank witness.  Nonzero rank modulo a prime
proves nonzero rational rank after denominator clearing.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import zipfile
from dataclasses import dataclass
from fractions import Fraction
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Iterator, Sequence

from dsf_ai_service.glew_runtime.global_uf import DSF_FIELD_ORDER
from tools.probe_auditory_full_field_separability_census import (
    ARCHIVE_SHA256,
    COMMANDS,
    _select_corpus,
)
from tools.probe_existing_auditory_neuron_temporal_go_no_go import (
    _mounts,
    _read_pcm,
)


SCHEMA = "guala.audit.auditory_causal_projective_span.v1"
PROFILE_ID = "guala.hearing.bilateral_causal_projective_cone.v1"
TEST_COMMANDS = COMMANDS[:3]
REFERENCE_COUNT = 5
HELD_OUT_COUNT = 1
PROOF_PRIMES = (2_305_843_009_213_693_951, 2_147_483_647)
EXPECTED_EAR_IDS = ("left", "right")
EXPECTED_CHANNEL_COUNT = 16
EXPECTED_FRAME_COUNT = 100
EXPECTED_COMPONENT_KINDS = ("pressure", "phase")


def _canonical(value: object) -> bytes:
    return json.dumps(
        value,
        allow_nan=False,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _digest(value: object) -> str:
    return hashlib.sha256(_canonical(value)).hexdigest()


@dataclass(frozen=True, slots=True)
class FullFieldCoordinate:
    ear_id: str
    cochlear_index: int
    source_index: int
    component_kind: str
    field_name: str

    def payload(self) -> list[object]:
        return [
            self.ear_id,
            self.cochlear_index,
            self.source_index,
            self.component_kind,
            self.field_name,
        ]


def _trajectory(
    settlement,
) -> Iterator[tuple[FullFieldCoordinate, Fraction]]:
    settlement.verify()
    if tuple(value.ear_id for value in settlement.ears) != EXPECTED_EAR_IDS:
        raise ValueError("projective trajectory lost bilateral topology")
    for ear in settlement.ears:
        channels = ear.event.channels
        if len(channels) != EXPECTED_CHANNEL_COUNT:
            raise ValueError("projective trajectory lost cochlear topology")
        for channel in channels:
            if (
                channel.cochlear_index < 0
                or len(channel.frames) != EXPECTED_FRAME_COUNT
            ):
                raise ValueError("projective trajectory cadence changed")
            for frame in channel.frames:
                field_tuples = (
                    channel.pressure_fields[
                        frame.pressure_field_tuple_index
                    ],
                    channel.phase_fields[
                        frame.phase_field_tuple_index
                    ],
                )
                for component_kind, field_tuple in zip(
                    EXPECTED_COMPONENT_KINDS,
                    field_tuples,
                    strict=True,
                ):
                    if (
                        tuple(name for name, _value in field_tuple.fields)
                        != DSF_FIELD_ORDER
                    ):
                        raise ValueError(
                            "projective trajectory flattened the DSF field"
                        )
                    for field_name, value in field_tuple.fields:
                        yield (
                            FullFieldCoordinate(
                                ear_id=ear.ear_id,
                                cochlear_index=channel.cochlear_index,
                                source_index=frame.source_index,
                                component_kind=component_kind,
                                field_name=field_name,
                            ),
                            value,
                        )


@lru_cache(maxsize=1_000_000)
def _residue(value: Fraction, prime: int) -> int:
    denominator = value.denominator % prime
    if denominator == 0:
        raise ValueError("proof prime divides an exact field denominator")
    return (
        (value.numerator % prime)
        * pow(denominator, prime - 2, prime)
    ) % prime


class _ModularRowBasis:
    def __init__(self, *, width: int, prime: int) -> None:
        if width < 1 or prime < 3:
            raise ValueError("modular rank authority changed")
        self._width = width
        self._prime = prime
        self._rows: dict[int, tuple[int, ...]] = {}
        self._pivot_coordinates: dict[int, FullFieldCoordinate] = {}

    @property
    def rank(self) -> int:
        return len(self._rows)

    @property
    def pivot_coordinates(self) -> tuple[FullFieldCoordinate, ...]:
        return tuple(
            self._pivot_coordinates[index]
            for index in sorted(self._rows)
        )

    def admit(
        self,
        row: Sequence[int],
        coordinate: FullFieldCoordinate,
    ) -> bool:
        if len(row) != self._width:
            raise ValueError("modular rank row width changed")
        values = [
            int(value) % self._prime
            for value in row
        ]
        for pivot in sorted(self._rows):
            coefficient = values[pivot]
            if coefficient:
                existing = self._rows[pivot]
                values = [
                    (
                        value
                        - coefficient * existing[index]
                    ) % self._prime
                    for index, value in enumerate(values)
                ]
        pivot = next(
            (
                index
                for index, value in enumerate(values)
                if value
            ),
            None,
        )
        if pivot is None:
            return False
        inverse = pow(values[pivot], self._prime - 2, self._prime)
        normalized = tuple(
            value * inverse % self._prime
            for value in values
        )
        self._rows[pivot] = normalized
        self._pivot_coordinates[pivot] = coordinate
        return True


def _aligned_rows(
    settlements: Sequence[object],
) -> Iterator[tuple[FullFieldCoordinate, tuple[Fraction, ...]]]:
    iterators = tuple(iter(_trajectory(value)) for value in settlements)
    coordinate_count = 0
    while True:
        current = []
        ended = []
        for iterator in iterators:
            try:
                current.append(next(iterator))
                ended.append(False)
            except StopIteration:
                ended.append(True)
        if any(ended):
            if not all(ended):
                raise ValueError("projective trajectories are not aligned")
            break
        coordinates = tuple(value[0] for value in current)
        if any(value != coordinates[0] for value in coordinates[1:]):
            raise ValueError("projective trajectory coordinate changed")
        coordinate_count += 1
        yield coordinates[0], tuple(value[1] for value in current)
    expected = (
        len(EXPECTED_EAR_IDS)
        * EXPECTED_CHANNEL_COUNT
        * EXPECTED_FRAME_COUNT
        * len(EXPECTED_COMPONENT_KINDS)
        * len(DSF_FIELD_ORDER)
    )
    if coordinate_count != expected:
        raise ValueError("projective trajectory cardinality changed")


def _rank(
    settlements: Sequence[object],
    *,
    prime: int,
) -> tuple[int, tuple[FullFieldCoordinate, ...]]:
    basis = _ModularRowBasis(
        width=len(settlements),
        prime=prime,
    )
    for coordinate, values in _aligned_rows(settlements):
        basis.admit(
            tuple(_residue(value, prime) for value in values),
            coordinate,
        )
        if basis.rank == len(settlements):
            break
    return basis.rank, basis.pivot_coordinates


def _relation(
    references: Sequence[object],
    query: object,
) -> dict[str, object]:
    proofs = []
    outside = False
    for prime in PROOF_PRIMES:
        reference_rank, reference_pivots = _rank(
            references,
            prime=prime,
        )
        augmented_rank, augmented_pivots = _rank(
            (*references, query),
            prime=prime,
        )
        proof = {
            "augmented_pivot_coordinates": [
                value.payload() for value in augmented_pivots
            ],
            "augmented_rank": augmented_rank,
            "prime": prime,
            "reference_pivot_coordinates": [
                value.payload() for value in reference_pivots
            ],
            "reference_rank": reference_rank,
        }
        proofs.append(proof)
        if augmented_rank > reference_rank:
            outside = True
            break
    return {
        "projective_cone_member": False if outside else None,
        "rational_span_member": False if outside else None,
        "rank_proofs": proofs,
        "state": (
            "proved_outside_rational_span"
            if outside
            else "indeterminate_requires_exact_cone_solver"
        ),
    }


def run(archive_path: Path) -> dict[str, object]:
    archive_sha256 = hashlib.sha256(archive_path.read_bytes()).hexdigest()
    if archive_sha256 != ARCHIVE_SHA256:
        raise ValueError("speech corpus archive authority changed")
    with zipfile.ZipFile(archive_path) as archive:
        corpus = _select_corpus(archive)
        references = tuple(
            item
            for command in TEST_COMMANDS
            for item in corpus
            if (
                item.oracle_command == command
                and item.split == "reference"
            )
        )
        held_out = tuple(
            next(
                item
                for item in corpus
                if (
                    item.oracle_command == command
                    and item.split == "held_out"
                )
            )
            for command in TEST_COMMANDS
        )
        ordered = (*references, *held_out)
        pcm = {
            item.item_id: _read_pcm(archive.read(item.archive_member))
            for item in ordered
        }
    if (
        len(references) != len(TEST_COMMANDS) * REFERENCE_COUNT
        or len(held_out) != len(TEST_COMMANDS) * HELD_OUT_COUNT
        or len({item.speaker_id for item in ordered}) != len(ordered)
    ):
        raise ValueError("projective corpus split changed")
    mounts = _mounts(ordered, pcm)
    references_by_command = {
        command: tuple(
            mounts[item.item_id].binaural_receptor_settlement
            for item in references
            if item.oracle_command == command
        )
        for command in TEST_COMMANDS
    }
    matrix = {
        query.item_id: {
            command: _relation(
                command_references,
                mounts[
                    query.item_id
                ].binaural_receptor_settlement,
            )
            for command, command_references
            in references_by_command.items()
        }
        for query in held_out
    }
    decisions = []
    for query in held_out:
        members = tuple(
            command
            for command, relation in matrix[query.item_id].items()
            if relation["projective_cone_member"] is True
        )
        decisions.append({
            "expected_grounding": query.oracle_command,
            "held_out_item_id": query.item_id,
            "projective_cone_members": list(members),
            "passed": members == (query.oracle_command,),
        })
    payload = {
        "archive_sha256": archive_sha256,
        "candidate_equation": (
            "B_T(n)={sum_i alpha_i X_i | alpha_i in Q_ge_0, "
            "X_i is a causally bound bilateral full-field trajectory}"
        ),
        "commands": list(TEST_COMMANDS),
        "decision_records": decisions,
        "ear_ids": list(EXPECTED_EAR_IDS),
        "field_order": list(DSF_FIELD_ORDER),
        "full_field_coordinate_count": (
            len(EXPECTED_EAR_IDS)
            * EXPECTED_CHANNEL_COUNT
            * EXPECTED_FRAME_COUNT
            * len(EXPECTED_COMPONENT_KINDS)
            * len(DSF_FIELD_ORDER)
        ),
        "held_out_pass_count": sum(
            value["passed"] for value in decisions
        ),
        "held_out_total": len(decisions),
        "l0_l4_modified": False,
        "matrix": matrix,
        "profile_id": PROFILE_ID,
        "schema": SCHEMA,
        "source_disjoint_speaker_count": len(ordered),
        "tutor_metadata_used_only_to_emulate_causal_thing_continuity": True,
    }
    return payload | {
        "authority_receipt_sha256": _digest(payload),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    report = run(args.archive)
    encoded = json.dumps(
        report,
        allow_nan=False,
        indent=2,
        sort_keys=True,
    ).encode("utf-8") + b"\n"
    if args.output is not None:
        args.output.write_bytes(encoded)
    print(encoded.decode("utf-8"))


if __name__ == "__main__":
    main()
