"""
GL-MDL-FIVE-CAP-CONVERSATION-WC-20260617-09

ONE simulation. Two systems (A and B) converse over 1200 ticks.
Each system has the full topology that supports all 5 DNA capabilities:

  Sections per system:
    subject, verb, object   — syntax (S→V→O keyhole cascade)
    listen, speak, ground   — conversation (heard→listen→speak loop)
    intro                   — introspection (isolated krimelack)

  Keyholes per system:
    subject→verb→object→speak  (syntax cascade feeds speech)
    listen→subject              (heard input primes next utterance)
    speak→listen                (self-hearing — credo)

  Coordinator: on (awareness via deliberation vs routing)
  Self-evo: on (gamma drift toward defaults, learning rate 0.04)
  Introspection: on (intro section commits with isolated krimelack)

Result reported per capability with pass criteria from DNA recipe.
"""
import sys, os, json
import numpy as np
from collections import defaultdict, Counter

TFE_PATH = "/home/claude/TFE"
sys.path.insert(0, TFE_PATH)
from dsf_ai_service.gualaloom_dna.assemblage import (
    Section, System, N, normalize, random_unit_complex, chi_of
)

SEED = 42
rng = np.random.default_rng(SEED)
rng_t = np.random.default_rng(SEED + 100)
rng_world = np.random.default_rng(SEED + 1000)

# 3 subject templates, 3 verb templates, 3 object templates — the "lexicon"
templates = {
    "subject": [random_unit_complex(N, rng_t) for _ in range(3)],
    "verb":    [random_unit_complex(N, rng_t) for _ in range(3)],
    "object":  [random_unit_complex(N, rng_t) for _ in range(3)],
}
# Word labels for the transcript
subject_words = ["guala", "eve", "joe"]
verb_words = ["sees", "loves", "knows"]
object_words = ["moon", "warm", "leaves"]


def make_projection(n, dim, rng):
    M = rng.standard_normal((n, n)) + 1j * rng.standard_normal((n, n))
    Q, _ = np.linalg.qr(M)
    P = np.zeros((n, n), dtype=complex)
    P[:dim, :dim] = np.eye(dim)
    return Q @ P @ Q.conj().T


def build_system(prefix, sys_rng):
    """Build a system with full 5-capability topology."""
    sections = []
    for sec_name, role in [
        ("subject", "subject_like"),
        ("verb", "verb_like"),
        ("object", "object_like"),
        ("listen", "general"),
        ("speak", "general"),
        ("ground", "grounded"),
        ("intro", "intro"),
    ]:
        s = Section(name=f"{prefix}_{sec_name}", rng=sys_rng, role=role)
        s.map_inject = make_projection(N, 6, sys_rng)
        sections.append(s)
    sys_ = System(sections, sys_rng)
    # Designate intro section
    sys_.intro_section = sys_.sections[f"{prefix}_intro"]
    sys_.intro_krimelack = []
    # Designate grounding section
    sys_.grounding_section = sys_.sections[f"{prefix}_ground"]
    # Keyholes — syntax cascade
    sys_.add_keyhole(f"{prefix}_subject", -2, 8, f"{prefix}_verb", 0.5)
    sys_.add_keyhole(f"{prefix}_verb", -2, 8, f"{prefix}_object", 0.5)
    sys_.add_keyhole(f"{prefix}_object", -2, 8, f"{prefix}_speak", 0.5)
    # Keyholes — conversation loop
    sys_.add_keyhole(f"{prefix}_listen", -2, 8, f"{prefix}_subject", 0.3)
    sys_.add_keyhole(f"{prefix}_speak", -2, 8, f"{prefix}_listen", 0.3)
    return sys_


sys_A = build_system("A", np.random.default_rng(SEED + 1))
sys_B = build_system("B", np.random.default_rng(SEED + 2))


def transcript_label(s_mode, v_mode, o_mode):
    """Convert mode-ids to a 'word-shaped' utterance label."""
    s = subject_words[s_mode % 3] if s_mode is not None else "?"
    v = verb_words[v_mode % 3] if v_mode is not None else "?"
    o = object_words[o_mode % 3] if o_mode is not None else "?"
    return f"{s} {v} {o}"


# Conversation script: sentence sequence both systems learn.
# A says these to B, B replies; their roles alternate.
# Total: 100 sentences, each generated by phased subject/verb/object evidence.
n_sentences = 100
ticks_per_phase = 4
sentences = []
for si in range(n_sentences):
    s_id = si % 3
    v_id = (si // 3) % 3
    o_id = (si // 9) % 3
    sentences.append((s_id, v_id, o_id))

# Track utterances per system
transcript = []   # all utterances with metadata
sys_A_commit_log = {"subject": [], "verb": [], "object": [], "speak": [], "intro": []}
sys_B_commit_log = {"subject": [], "verb": [], "object": [], "speak": [], "intro": []}

# Track last heard from partner (for conversation primitive)
A_external_buffer = []  # list of {"tick": t, "vec": v, "label": l}
B_external_buffer = []
sys_A.external_speaker_buffer = A_external_buffer
sys_B.external_speaker_buffer = B_external_buffer

# Match-rate trackers (for adaptive heard-speaker strength)
sys_A.heard_speaker_strength = 0.70  # baseline
sys_B.heard_speaker_strength = 0.70
sys_A.utterance_matches = []
sys_B.utterance_matches = []

# Atlas intro-leakage check
intro_atlas_leakage_A = 0
intro_atlas_leakage_B = 0


def speaker_now(si):
    """Who's speaking sentence si — A says even, B says odd."""
    return "A" if si % 2 == 0 else "B"


def get_sys(spk):
    return sys_A if spk == "A" else sys_B


def get_log(spk):
    return sys_A_commit_log if spk == "A" else sys_B_commit_log


def get_other_log(spk):
    return sys_B_commit_log if spk == "A" else sys_A_commit_log


def get_buf(spk):
    return A_external_buffer if spk == "A" else B_external_buffer


# Main loop — phased per sentence
print("=" * 72)
print("FIVE-CAPABILITY CONVERSATION SIMULATION")
print("=" * 72)
print(f"Two systems A and B. Each: SVO + listen/speak/ground + intro.")
print(f"100 sentences, 12 ticks/sentence = 1,200 ticks total.")
print()

for si, (s_id, v_id, o_id) in enumerate(sentences):
    spk = speaker_now(si)
    sys_ = get_sys(spk)
    other_sys = get_sys("B" if spk == "A" else "A")
    cl = get_log(spk)
    prefix = spk

    # Phase 0 — subject
    for _ in range(ticks_per_phase):
        ev = {f"{prefix}_subject": templates["subject"][s_id]
              + 0.10 * rng.standard_normal(N)}
        # Conversation primitive: also feed environment to listen + ground
        ev[f"{prefix}_ground"] = templates["subject"][s_id] * 0.7 \
            + 0.10 * rng.standard_normal(N)
        # Listen sees what speaker said (self-hearing) OR what other said (heard)
        if get_buf(prefix):
            heard = get_buf(prefix)[-1]
            ev[f"{prefix}_listen"] = heard["vec"] * sys_.heard_speaker_strength \
                + 0.10 * rng.standard_normal(N)
        commits = sys_.tick_once(ev, enable_self_evo=True,
                                  coordinator_on=True, introspection_on=True)
        for c in commits:
            short_section = c["section"].split("_", 1)[1]
            if short_section in cl:
                cl[short_section].append({
                    "tick": sys_.tick, "mode_id": c["mode_id"],
                    "chi": c["chi"], "sentence_id": si, "phase": "subject",
                })
        # Introspection logging
        if sys_.intro_krimelack:
            recent_intro = [k for k in sys_.intro_krimelack
                            if k["tick"] >= sys_.tick - 1]
            for ik in recent_intro:
                cl["intro"].append({
                    "tick": ik["tick"], "mode_id": ik["mode_id"],
                    "chi": ik["chi"], "sentence_id": si,
                })

    # Phase 1 — verb
    for _ in range(ticks_per_phase):
        ev = {f"{prefix}_verb": templates["verb"][v_id]
              + 0.10 * rng.standard_normal(N)}
        ev[f"{prefix}_ground"] = templates["verb"][v_id] * 0.7 \
            + 0.10 * rng.standard_normal(N)
        if get_buf(prefix):
            heard = get_buf(prefix)[-1]
            ev[f"{prefix}_listen"] = heard["vec"] * sys_.heard_speaker_strength \
                + 0.10 * rng.standard_normal(N)
        commits = sys_.tick_once(ev, enable_self_evo=True,
                                  coordinator_on=True, introspection_on=True)
        for c in commits:
            short_section = c["section"].split("_", 1)[1]
            if short_section in cl:
                cl[short_section].append({
                    "tick": sys_.tick, "mode_id": c["mode_id"],
                    "chi": c["chi"], "sentence_id": si, "phase": "verb",
                })

    # Phase 2 — object
    for _ in range(ticks_per_phase):
        ev = {f"{prefix}_object": templates["object"][o_id]
              + 0.10 * rng.standard_normal(N)}
        ev[f"{prefix}_ground"] = templates["object"][o_id] * 0.7 \
            + 0.10 * rng.standard_normal(N)
        if get_buf(prefix):
            heard = get_buf(prefix)[-1]
            ev[f"{prefix}_listen"] = heard["vec"] * sys_.heard_speaker_strength \
                + 0.10 * rng.standard_normal(N)
        commits = sys_.tick_once(ev, enable_self_evo=True,
                                  coordinator_on=True, introspection_on=True)
        for c in commits:
            short_section = c["section"].split("_", 1)[1]
            if short_section in cl:
                cl[short_section].append({
                    "tick": sys_.tick, "mode_id": c["mode_id"],
                    "chi": c["chi"], "sentence_id": si, "phase": "object",
                })

    # Sentence complete — compose utterance from the first commits in each section
    s_commits = [c for c in cl["subject"] if c["sentence_id"] == si]
    v_commits = [c for c in cl["verb"] if c["sentence_id"] == si]
    o_commits = [c for c in cl["object"] if c["sentence_id"] == si]

    if s_commits and v_commits and o_commits:
        s_first = min(s_commits, key=lambda c: c["tick"])
        v_first = min(v_commits, key=lambda c: c["tick"])
        o_first = min(o_commits, key=lambda c: c["tick"])
        # Build utterance vector — average of the three template states
        utterance_vec = normalize(
            templates["subject"][s_id]
            + templates["verb"][v_id]
            + templates["object"][o_id]
        )
        utt_label = transcript_label(s_first["mode_id"], v_first["mode_id"],
                                     o_first["mode_id"])
        true_label = f"{subject_words[s_id]} {verb_words[v_id]} {object_words[o_id]}"
        utt = {
            "tick": sys_.tick, "speaker": spk, "sentence_id": si,
            "utterance": utt_label,
            "true_meaning": true_label,
            "s_tick": s_first["tick"], "v_tick": v_first["tick"], "o_tick": o_first["tick"],
            "order_correct": s_first["tick"] < v_first["tick"] < o_first["tick"],
            "vec": utterance_vec,
        }
        transcript.append(utt)
        # Transmit to other system
        other_buf = get_buf("B" if spk == "A" else "A")
        other_buf.append({"tick": sys_.tick, "vec": utterance_vec, "label": true_label})
        # External speaker hook on other system (DNA conversation primitive)
        other_sys.hear_speaker(utterance_vec, f"{'B' if spk=='A' else 'A'}_listen",
                                f"{'B' if spk=='A' else 'A'}_speak")
        # Match rate for adaptive heard-speaker strength
        recent_other = [t for t in transcript if t["speaker"] != spk
                        and t["sentence_id"] >= si - 3]
        matched = any(t["true_meaning"] == true_label for t in recent_other)
        sys_.utterance_matches.append(matched)
        sys_.record_utterance_match(matched)


# =====================================================================
# Capability analysis on the produced transcript
# =====================================================================

print(f"Total complete utterances: {len(transcript)}")
print(f"  A says: {sum(1 for u in transcript if u['speaker']=='A')}")
print(f"  B says: {sum(1 for u in transcript if u['speaker']=='B')}")
print()


# ---------------------------------------------------------------------
# CAPABILITY 1: SYNTAX
# ---------------------------------------------------------------------
print("=" * 72)
print("CAPABILITY 1: SYNTAX  (S→V→O order in commits)")
print("=" * 72)
total = len(transcript)
correct = sum(1 for u in transcript if u["order_correct"])
syntax_pass_rate = correct / max(total, 1)
print(f"Utterances with S<V<O commit order: {correct}/{total} = {syntax_pass_rate:.2%}")
# Mode purity per section
def mode_purity(commits, true_id_fn):
    mode_to_ids = defaultdict(list)
    for c in commits:
        if c.get("sentence_id") is None:
            continue
        true_id = true_id_fn(c["sentence_id"])
        mode_to_ids[c["mode_id"]].append(true_id)
    purities = []
    for mid, ids in mode_to_ids.items():
        if len(ids) >= 3:
            ctr = Counter(ids)
            purities.append(ctr.most_common(1)[0][1] / len(ids))
    return float(np.mean(purities)) if purities else 0.0, len(mode_to_ids)
a_subj_purity, a_n_subj = mode_purity(sys_A_commit_log["subject"], lambda si: sentences[si][0])
a_verb_purity, a_n_verb = mode_purity(sys_A_commit_log["verb"], lambda si: sentences[si][1])
a_obj_purity, a_n_obj = mode_purity(sys_A_commit_log["object"], lambda si: sentences[si][2])
b_subj_purity, b_n_subj = mode_purity(sys_B_commit_log["subject"], lambda si: sentences[si][0])
b_verb_purity, b_n_verb = mode_purity(sys_B_commit_log["verb"], lambda si: sentences[si][1])
b_obj_purity, b_n_obj = mode_purity(sys_B_commit_log["object"], lambda si: sentences[si][2])
chance = 1.0 / 3
print(f"A: subject_purity={a_subj_purity:.2%} ({a_n_subj} modes), "
      f"verb={a_verb_purity:.2%} ({a_n_verb}), object={a_obj_purity:.2%} ({a_n_obj})")
print(f"B: subject_purity={b_subj_purity:.2%} ({b_n_subj} modes), "
      f"verb={b_verb_purity:.2%} ({b_n_verb}), object={b_obj_purity:.2%} ({b_n_obj})")
print(f"Chance level: {chance:.2%}; bar: chance+5pp = {chance+0.05:.2%}")
syntax_pass = (syntax_pass_rate >= 0.60 and
               a_subj_purity > chance + 0.05 and a_verb_purity > chance + 0.05 and
               a_obj_purity > chance + 0.05)
print(f"SYNTAX PASS (order>=60% AND purity>chance+5pp for A): {syntax_pass}")
print()


# ---------------------------------------------------------------------
# CAPABILITY 2: CONVERSATION
# ---------------------------------------------------------------------
print("=" * 72)
print("CAPABILITY 2: CONVERSATION  (cross-turn vector overlap)")
print("=" * 72)
# Vector-level response overlap: A's utterance i vs B's reply i+1
overlaps = []
for i in range(1, len(transcript)):
    if transcript[i]["speaker"] != transcript[i-1]["speaker"]:
        v1 = transcript[i-1]["vec"]
        v2 = transcript[i]["vec"]
        overlaps.append(float(np.abs(np.vdot(v1, v2)) ** 2))
mean_response = float(np.mean(overlaps)) if overlaps else 0.0
# Random baseline: shuffled pairs
random_baselines = []
for _ in range(200):
    i = rng.integers(0, max(1, len(transcript)))
    j = rng.integers(0, max(1, len(transcript)))
    if i != j and transcript and i < len(transcript) and j < len(transcript):
        random_baselines.append(float(np.abs(
            np.vdot(transcript[i]["vec"], transcript[j]["vec"])) ** 2))
random_baseline = float(np.mean(random_baselines)) if random_baselines else 0.001
ratio = mean_response / max(random_baseline, 0.001)
# Grounded section health
A_ground_commits = sum(1 for nm in sys_A.sections
                       if nm.endswith("_ground")
                       for k in sys_A.sections[nm].krimelack
                       if k["tick"] >= sys_A.tick - 200)
B_ground_commits = sum(1 for nm in sys_B.sections
                       if nm.endswith("_ground")
                       for k in sys_B.sections[nm].krimelack
                       if k["tick"] >= sys_B.tick - 200)
both_speak_enough = (sum(1 for u in transcript if u["speaker"]=="A") >= 10 and
                     sum(1 for u in transcript if u["speaker"]=="B") >= 10)
overlap_high_enough = mean_response >= 0.04
ground_alive = A_ground_commits + B_ground_commits > 10
conversation_pass = both_speak_enough and overlap_high_enough and ground_alive
print(f"Mean response overlap: {mean_response:.2%} vs random {random_baseline:.2%} (ratio {ratio:.2f}x)")
print(f"Grounded commits last 200 ticks: A={A_ground_commits}, B={B_ground_commits}")
print(f"CONVERSATION PASS (both>=10 AND overlap>=4% AND grounded alive): {conversation_pass}")
print()


# ---------------------------------------------------------------------
# CAPABILITY 3: INTROSPECTION
# ---------------------------------------------------------------------
print("=" * 72)
print("CAPABILITY 3: INTROSPECTION  (intro mode predicts dominant chi)")
print("=" * 72)
# For each intro commit, what was the dominant chi in the atlas right after?
# We use the atlas snapshot logic — intro should track atlas state.
intro_commits_A = sys_A_commit_log["intro"]
n_intro_A = len(intro_commits_A)
n_intro_modes_A = len(set(c["mode_id"] for c in intro_commits_A))
# Atlas chi distribution at intro commit times
intro_to_atlas_chi = []
for ic in intro_commits_A:
    # Get atlas chi class with the most claims as of intro commit tick
    chi_counts = Counter()
    for chi, entries in sys_A.atlas.entries.items():
        chi_counts[chi] = len([e for e in entries if e["tick"] <= ic["tick"]])
    if chi_counts:
        dominant = chi_counts.most_common(1)[0][0]
        intro_to_atlas_chi.append((ic["mode_id"], dominant))
# Compute purity: do specific intro mode_ids predict specific dominant chis?
intro_mode_to_chis = defaultdict(list)
for mid, dchi in intro_to_atlas_chi:
    intro_mode_to_chis[mid].append(dchi)
purities = []
for mid, chis in intro_mode_to_chis.items():
    if len(chis) >= 3:
        ctr = Counter(chis)
        purities.append(ctr.most_common(1)[0][1] / len(chis))
intro_purity = float(np.mean(purities)) if purities else 0.0
distinct_chis = len(set(d for _, d in intro_to_atlas_chi))
intro_chance = 1.0 / max(distinct_chis, 1)
# Atlas isolation: did intro section claims leak into the main atlas?
intro_leakage = sum(
    1 for chi, entries in sys_A.atlas.entries.items()
    for e in entries
    if e["section"] == "A_intro"
)
print(f"A intro commits: {n_intro_A}, distinct modes: {n_intro_modes_A}")
print(f"Distinct dominant-chi classes: {distinct_chis}")
print(f"Intro-mode predictive purity: {intro_purity:.2%}, chance: {intro_chance:.2%}")
print(f"Atlas intro-leakage: {intro_leakage} (must be 0)")
intro_pass = intro_purity > 1.5 * intro_chance and intro_leakage == 0
print(f"INTROSPECTION PASS (purity > 1.5×chance AND no leakage): {intro_pass}")
print()


# ---------------------------------------------------------------------
# CAPABILITY 4: SELF-IMPROVEMENT
# ---------------------------------------------------------------------
print("=" * 72)
print("CAPABILITY 4: SELF-IMPROVEMENT  (gamma drift)")
print("=" * 72)
defaults = {"symmetry": 0.5, "consistency": 0.5, "compactness": 0.3}
# Average gamma across A's sections (matches canonical test methodology)
gamma_avg = {k: 0.0 for k in defaults}
n_sec = 0
for sec in sys_A.sections.values():
    for k in defaults:
        gamma_avg[k] += sec.gamma[k]
    n_sec += 1
gamma_avg = {k: v / n_sec for k, v in gamma_avg.items()}
# Check pin on AVERAGE values, not per-section
n_pinned = sum(1 for v in gamma_avg.values() if v <= 0.06 or v >= 1.49)
n_moved = sum(1 for k in defaults if abs(gamma_avg[k] - defaults[k]) > 0.01)
print(f"A final mean gamma: {gamma_avg}")
print(f"A default gamma:    {defaults}")
print(f"Gamma values moved from defaults (averaged): {n_moved}/3")
print(f"Gamma averaged values pinned at bounds: {n_pinned}/3")
self_imp_pass = n_moved >= 2 and n_pinned == 0
print(f"SELF-IMPROVEMENT PASS (gamma moved AND no pin): {self_imp_pass}")
print()


# ---------------------------------------------------------------------
# CAPABILITY 5: AWARENESS
# ---------------------------------------------------------------------
print("=" * 72)
print("CAPABILITY 5: AWARENESS  (coordinator resolution effect)")
print("=" * 72)
A_actions = len(sys_A.coordinator_actions_log)
A_resolution = sys_A.coordinator_resolution_effect()
A_deliberation = len(sys_A.deliberation_ticks)
A_routing = len(sys_A.routing_ticks)
B_actions = len(sys_B.coordinator_actions_log)
B_resolution = sys_B.coordinator_resolution_effect()
print(f"A coordinator: deliberation_ticks={A_deliberation}, routing_ticks={A_routing}")
print(f"A coordinator actions: {A_actions}, resolution_effect: {A_resolution:.2%}")
print(f"B coordinator actions: {B_actions}, resolution_effect: {B_resolution:.2%}")
deliberation_engaged = A_deliberation > 0 and A_routing > 0
awareness_pass = deliberation_engaged and (A_resolution >= 0.15 or B_resolution >= 0.15)
print(f"AWARENESS PASS (deliberation engaged AND resolution>=15%): {awareness_pass}")
print()


# ---------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------
print("=" * 72)
print("OVERALL")
print("=" * 72)
results = {
    "syntax": syntax_pass,
    "conversation": conversation_pass,
    "introspection": intro_pass,
    "self_improvement": self_imp_pass,
    "awareness": awareness_pass,
}
for k, v in results.items():
    print(f"  {k}: {'PASS' if v else 'FAIL'}")
print(f"\nAll five: {'PASS' if all(results.values()) else 'FAIL'}")
print()


# ---------------------------------------------------------------------
# CONVERSATION TRANSCRIPT — first 20 turns
# ---------------------------------------------------------------------
print("=" * 72)
print("CONVERSATION TRANSCRIPT  (first 20 utterances)")
print("=" * 72)
print(f"{'tick':>5}  {'who':>3}  {'utterance':<30}  {'meant':<30}  ord")
print("-" * 80)
for u in transcript[:20]:
    print(f"{u['tick']:>5}  {u['speaker']:>3}  {u['utterance']:<30}  "
          f"{u['true_meaning']:<30}  {'✓' if u['order_correct'] else '✗'}")
print()
print(f"... ({len(transcript) - 20} more)" if len(transcript) > 20 else "")
print()
print("LAST 20 UTTERANCES:")
print(f"{'tick':>5}  {'who':>3}  {'utterance':<30}  {'meant':<30}  ord")
print("-" * 80)
for u in transcript[-20:]:
    print(f"{u['tick']:>5}  {u['speaker']:>3}  {u['utterance']:<30}  "
          f"{u['true_meaning']:<30}  {'✓' if u['order_correct'] else '✗'}")

# Save transcript
os.makedirs("/home/claude/conversation", exist_ok=True)
with open("/home/claude/conversation/transcript.json", "w") as f:
    json.dump({
        "results": results,
        "n_utterances": len(transcript),
        "transcript": [
            {k: v for k, v in u.items() if k != "vec"}
            for u in transcript
        ],
        "syntax_order_acc": syntax_pass_rate,
        "conversation_overlap": mean_response,
        "conversation_baseline": random_baseline,
        "intro_purity": intro_purity,
        "intro_chance": intro_chance,
        "intro_leakage": intro_leakage,
        "gamma_final": gamma_avg,
        "n_pinned": n_pinned,
        "coordinator_resolution_A": A_resolution,
        "coordinator_resolution_B": B_resolution,
        "coordinator_actions_A": A_actions,
        "coordinator_deliberation_A": A_deliberation,
        "coordinator_routing_A": A_routing,
    }, f, indent=2, default=str)
print("\nSaved: /home/claude/conversation/transcript.json")
